import type { MutationDef, Stage } from './types'

export const SAVE_KEY = 'evolve.save.v1'

/** The evolutionary ladder. The final stage has no further evolution. */
export const STAGES: Stage[] = [
  {
    id: 'cell',
    name: 'Single Cell',
    emoji: '🦠',
    blurb: 'A lone speck of life adrift in the primordial soup.',
    evolveCost: 100,
    dnaReward: 1,
  },
  {
    id: 'colony',
    name: 'Cell Colony',
    emoji: '🫧',
    blurb: 'Many cells, one purpose. Cooperation is a superpower.',
    evolveCost: 1_200,
    dnaReward: 3,
  },
  {
    id: 'fish',
    name: 'Fish',
    emoji: '🐟',
    blurb: 'You grew a spine and slipped through ancient seas.',
    evolveCost: 15_000,
    dnaReward: 8,
  },
  {
    id: 'amphibian',
    name: 'Amphibian',
    emoji: '🐸',
    blurb: 'The first bold crawl onto dry land.',
    evolveCost: 120_000,
    dnaReward: 20,
  },
  {
    id: 'reptile',
    name: 'Reptile',
    emoji: '🦎',
    blurb: 'Scales, eggs, and a taste for sunlit rocks.',
    evolveCost: 900_000,
    dnaReward: 50,
  },
  {
    id: 'mammal',
    name: 'Mammal',
    emoji: '🐭',
    blurb: 'Warm blood and warmer instincts.',
    evolveCost: 7_000_000,
    dnaReward: 120,
  },
  {
    id: 'primate',
    name: 'Primate',
    emoji: '🐒',
    blurb: 'Opposable thumbs change everything.',
    evolveCost: 50_000_000,
    dnaReward: 300,
  },
  {
    id: 'human',
    name: 'Thinking Being',
    emoji: '🧑\u200d🚀',
    blurb: 'You gaze at the stars and wonder what comes next.',
    evolveCost: Infinity,
    dnaReward: 0,
  },
]

export const MUTATIONS: MutationDef[] = [
  {
    id: 'membrane',
    name: 'Permeable Membrane',
    emoji: '🧫',
    description: 'Absorb ambient energy passively.',
    baseCost: 15,
    costGrowth: 1.15,
    eps: 0.2,
    clickBonus: 0,
    unlockStage: 0,
  },
  {
    id: 'mitochondria',
    name: 'Mitochondria',
    emoji: '⚡',
    description: 'The powerhouse of the cell. More energy per click.',
    baseCost: 50,
    costGrowth: 1.17,
    eps: 0,
    clickBonus: 1,
    unlockStage: 0,
  },
  {
    id: 'cilia',
    name: 'Cilia',
    emoji: '🌾',
    description: 'Tiny oars that sweep in a steady current of energy.',
    baseCost: 220,
    costGrowth: 1.16,
    eps: 1.5,
    clickBonus: 0,
    unlockStage: 1,
  },
  {
    id: 'photosynthesis',
    name: 'Photosynthesis',
    emoji: '🌿',
    description: 'Turn light into a reliable stream of energy.',
    baseCost: 1_200,
    costGrowth: 1.15,
    eps: 8,
    clickBonus: 0,
    unlockStage: 1,
  },
  {
    id: 'gills',
    name: 'Gills',
    emoji: '🐠',
    description: 'Extract energy from flowing water.',
    baseCost: 9_000,
    costGrowth: 1.15,
    eps: 45,
    clickBonus: 4,
    unlockStage: 2,
  },
  {
    id: 'lungs',
    name: 'Lungs',
    emoji: '🫁',
    description: 'Breathe air, unlock a whole new world of energy.',
    baseCost: 70_000,
    costGrowth: 1.15,
    eps: 260,
    clickBonus: 0,
    unlockStage: 3,
  },
  {
    id: 'limbs',
    name: 'Limbs',
    emoji: '🦿',
    description: 'Roam farther, forage more per click.',
    baseCost: 550_000,
    costGrowth: 1.15,
    eps: 0,
    clickBonus: 40,
    unlockStage: 4,
  },
  {
    id: 'warmblood',
    name: 'Warm Blood',
    emoji: '🔥',
    description: 'Stay active day and night for constant energy.',
    baseCost: 4_000_000,
    costGrowth: 1.15,
    eps: 1_600,
    clickBonus: 0,
    unlockStage: 5,
  },
  {
    id: 'brain',
    name: 'Big Brain',
    emoji: '🧠',
    description: 'Plan, tool-make, and multiply every effort.',
    baseCost: 30_000_000,
    costGrowth: 1.15,
    eps: 9_000,
    clickBonus: 250,
    unlockStage: 6,
  },
]

/** Each accumulated DNA point adds this fraction to all energy production. */
export const DNA_BONUS_PER_POINT = 0.02

/** Each stage beyond the first multiplies production by this factor. */
export const STAGE_MULTIPLIER = 1.9
