import type { EraDef, StageId } from './types';

export const STAGE_ORDER: StageId[] = [
  'microbe',
  'multicell',
  'fish',
  'amphibian',
  'reptile',
  'mammal',
  'primate',
  'human',
  'tribe',
  'ending',
];

export const eras: EraDef[] = [
  {
    id: 'microbe',
    label: '太古宙 · 微生物',
    yearLabel: '约 38 亿年前',
    yearMa: 3800,
    form: '单细胞原核生物',
    milestoneTitle: '深渊之始',
    milestoneText:
      '【固有进化】太古宙的海底热泉口喷出硫化物与热能。你是一粒半透明单细胞，没有眼睛，只靠化学梯度感知世界。\n\n氧气尚未充盈大气，陆地荒芜，海洋是唯一的舞台。',
    eventsBeforeNext: 3,
    baseEnvironment: {
      habitat: '深海热泉口周围的矿物烟柱带',
      climate: '还原性大气，无臭氧层，海面紫外线极强',
      suitability: 62,
      threats: ['噬菌体爆发', '热泉温度骤变', '紫外线（若上浮）', '化学毒素脉冲'],
      opportunities: ['硫化物产能', '基因水平转移', '矿物缝隙庇护'],
      nearbyLife: ['嗜热古菌', '原始细菌群落', '可能存在的病毒样粒子'],
      notes: '此时几乎没有多细胞动物；“猎手”主要是更大的微生物与病毒。',
    },
    choices: [
      {
        id: 'chemo',
        text: '固守热泉，走化能合成路线',
        enterEvents: true,
        gainTrait: '化能耐热',
        fitnessDelta: 5,
      },
      {
        id: 'photo',
        text: '尝试靠近有光水层',
        dangerHint: '紫外线可能直接杀死细胞',
        successRate: 0.55,
        enterEvents: true,
        gainTrait: '光合萌芽',
        fitnessDelta: 8,
        failText: '海面的紫外线撕开了细胞膜，你在接近光明时消散。',
      },
      {
        id: 'gene',
        text: '与邻近细胞交换基因片段',
        dangerHint: '可能引入致命缺陷',
        successRate: 0.6,
        enterEvents: true,
        gainTrait: '基因可塑性',
        fitnessDelta: 6,
        failText: '外来基因毁掉了复制酶，这一系就此绝灭。',
      },
      {
        id: 'drift',
        text: '附着碎屑随暗流扩散',
        enterEvents: true,
        gainTrait: '扩散殖民',
        fitnessDelta: 3,
      },
    ],
  },
  {
    id: 'multicell',
    label: '元古宙末 · 多细胞',
    yearLabel: '约 6 亿年前',
    yearMa: 600,
    form: '简单多细胞软体生物',
    milestoneTitle: '细胞开始分工',
    milestoneText:
      '【固有进化】氧含量上升，雪球地球的阴影逐渐退去。你的细胞开始粘连、分工：外层感知，内层消化。\n\n伊迪卡拉纪的奇特生命正铺满浅海。',
    eventsBeforeNext: 3,
    baseEnvironment: {
      habitat: '大陆架浅海与潮下带软泥',
      climate: '氧气上升，气候波动仍大，局部冰川残留',
      suitability: 58,
      threats: ['大型滤食/刮食生物', '风暴掀底', '局部缺氧盆地', '海底火山喷发'],
      opportunities: ['富氧促进体型增大', '藻席提供稳定食物', '固着与漂浮两种生态位'],
      nearbyLife: ['叠层石藻席', '奇异伊迪卡拉生物', '早期两侧对称蠕虫样动物'],
      notes: '尚无真正的硬骨鱼类；威胁来自更大的软躯体生物与环境灾变。',
    },
    choices: [
      {
        id: 'sessile',
        text: '固着滤食，稳扎礁缘',
        enterEvents: true,
        gainTrait: '固着滤食',
        fitnessDelta: 4,
      },
      {
        id: 'mobile',
        text: '发展肌肉纤维，短距爬行猎食',
        dangerHint: '更易被更大软体生物发现',
        successRate: 0.6,
        enterEvents: true,
        gainTrait: '原始运动',
        fitnessDelta: 7,
        failText: '你刚学会爬行，就被一张更大的口幕吞没。',
      },
      {
        id: 'float',
        text: '充气漂浮，追随浮游食物',
        enterEvents: true,
        gainTrait: '浮游生活',
        fitnessDelta: 5,
      },
      {
        id: 'bury',
        text: '埋栖避险，只露取食管',
        enterEvents: true,
        gainTrait: '埋栖',
        fitnessDelta: 5,
      },
    ],
  },
  {
    id: 'fish',
    label: '古生代 · 鱼类',
    yearLabel: '约 4.2 亿年前',
    yearMa: 420,
    form: '有颌鱼类',
    milestoneTitle: '鳍与脊索',
    milestoneText:
      '【固有进化】寒武纪大爆发的余波之后，你演化出脊索、鳍与颌。海洋第一次出现真正高效的主动猎手。\n\n盔甲鱼、棘鱼与早期鲨鱼类亲属在同一片海里竞争。',
    eventsBeforeNext: 3,
    baseEnvironment: {
      habitat: '近岸珊瑚礁、潟湖与开阔陆架海',
      climate: '总体温暖，海平面较高',
      suitability: 64,
      threats: ['更大的有颌掠食鱼', '甲胄鱼冲撞', '缺氧事件', '海啸与风暴'],
      opportunities: ['丰富的无脊椎猎物', '鱼群协作', '河口避难所'],
      nearbyLife: ['三叶虫', '头足类', '海蝎', '早期有颌鱼', '珊瑚与海百合'],
      notes: '陆地仍几乎没有脊椎动物；主要舞台在海里。',
    },
    choices: [
      {
        id: 'school',
        text: '加入鱼群，换取警戒',
        enterEvents: true,
        gainTrait: '群游',
        fitnessDelta: 5,
      },
      {
        id: 'hunter',
        text: '强化颌齿，做独行猎手',
        dangerHint: '落单易成巨口晚餐',
        successRate: 0.55,
        enterEvents: true,
        gainTrait: '掠食颌',
        fitnessDelta: 8,
        failText: '阴影从下方升起，利齿合拢，海面只剩涟漪。',
      },
      {
        id: 'bottom',
        text: '贴底伪装，避开开阔水域',
        enterEvents: true,
        gainTrait: '底栖伪装',
        fitnessDelta: 4,
      },
      {
        id: 'estuary',
        text: '开拓河口半咸水地带',
        dangerHint: '盐度剧变可能致命',
        successRate: 0.55,
        enterEvents: true,
        gainTrait: '广盐适应',
        fitnessDelta: 7,
        failText: '渗透压失衡，鳃丝在淡咸水交界处失效。',
      },
    ],
  },
  {
    id: 'amphibian',
    label: '泥盆—石炭 · 两栖',
    yearLabel: '约 3.6 亿年前',
    yearMa: 360,
    form: '早期四足动物（两栖类）',
    milestoneTitle: '登陆者',
    milestoneText:
      '【固有进化】鳍骨变成粗笨四肢，你把身体撑出水面。空气刺痛潮湿皮肤，但陆地几乎没有脊椎竞争者。\n\n蕨类沼泽在月光下延展，巨型节肢动物已在岸边等待。',
    eventsBeforeNext: 3,
    baseEnvironment: {
      habitat: '潮间带泥滩、淡水沼泽与河岸',
      climate: '温暖湿润，氧气偏高，适合巨大节肢动物',
      suitability: 52,
      threats: ['脱水', '巨型蜈蚣/蝎类', '水边伏击鱼', '干旱断流'],
      opportunities: ['无脊椎动物饵料丰富', '浅滩产卵', '夜间保湿活动'],
      nearbyLife: ['早期陆生植物', '巨脉蜻蜓祖先', '倍足类', '肺鱼与残存盾皮鱼'],
      notes: '羊膜卵尚未出现，你仍高度依赖水体繁殖。',
    },
    choices: [
      {
        id: 'night',
        text: '只在夜晚上岸，避开烈日',
        enterEvents: true,
        gainTrait: '夜行保湿',
        fitnessDelta: 6,
      },
      {
        id: 'bask',
        text: '白天晒太阳加速代谢',
        dangerHint: '干燥与天敌双重威胁',
        successRate: 0.5,
        enterEvents: true,
        gainTrait: '嗜热代谢',
        fitnessDelta: 7,
        failText: '阳光抽走最后水分，你干枯在泥滩上。',
      },
      {
        id: 'pool',
        text: '固守潮池，半水半陆',
        enterEvents: true,
        gainTrait: '潮池专家',
        fitnessDelta: 4,
      },
      {
        id: 'inland',
        text: '沿湿润走廊向内陆推进',
        dangerHint: '远离水源风险高',
        successRate: 0.5,
        enterEvents: true,
        gainTrait: '内陆拓殖',
        fitnessDelta: 8,
        failText: '河床断流，你倒在开裂的淤泥里。',
      },
    ],
  },
  {
    id: 'reptile',
    label: '中生代前奏 · 爬行',
    yearLabel: '约 3 亿年前',
    yearMa: 300,
    form: '早期羊膜动物 / 爬行类',
    milestoneTitle: '鳞甲与羊膜卵',
    milestoneText:
      '【固有进化】干燥鳞片与羊膜卵让你摆脱水体束缚。石炭—二叠的森林与旱原成为新家园。\n\n巨大化与穴居两条路同时敞开。',
    eventsBeforeNext: 3,
    baseEnvironment: {
      habitat: '旱季明显的森林边缘、河谷与岩缝',
      climate: '二叠纪前后气候趋向干旱与剧烈波动',
      suitability: 60,
      threats: ['大型肉食合弓类/爬行类', '长期干旱', '森林野火', '食物链崩溃'],
      opportunities: ['羊膜卵远离水域', '甲胄防御', '夜行小型生态位'],
      nearbyLife: ['种子蕨', '早期针叶植物', '盘龙类', '大型两栖残留', '昆虫辐射'],
      notes: '恐龙时代尚未完全到来，但陆生脊椎竞争已白热化。',
    },
    choices: [
      {
        id: 'huge',
        text: '追求体型，称霸开阔地',
        dangerHint: '灾变时巨兽更难存活',
        successRate: 0.5,
        enterEvents: true,
        gainTrait: '巨体',
        fitnessDelta: 6,
        failText: '旱季饿死了过于庞大的身体。',
      },
      {
        id: 'small',
        text: '保持小巧，钻缝夜行',
        enterEvents: true,
        gainTrait: '缝隙生存',
        fitnessDelta: 5,
      },
      {
        id: 'armor',
        text: '加厚甲片走防御路线',
        enterEvents: true,
        gainTrait: '骨板甲胄',
        fitnessDelta: 5,
      },
      {
        id: 'enduro',
        text: '提高活动代谢，为温血铺路',
        dangerHint: '能量消耗巨大',
        successRate: 0.55,
        enterEvents: true,
        gainTrait: '高代谢',
        fitnessDelta: 9,
        failText: '寒冷夜里脂肪燃尽，你未能醒来。',
      },
    ],
  },
  {
    id: 'mammal',
    label: '中生代—新生代 · 哺乳',
    yearLabel: '约 6600 万年前',
    yearMa: 66,
    form: '早期哺乳动物',
    milestoneTitle: '温血萌生',
    milestoneText:
      '【固有进化】在恐龙帝国的夹缝与崩塌之后，皮毛、乳汁与恒温让你抓住了机会。\n\n陨星冬天过去，小型夜行者正在继承白天。',
    eventsBeforeNext: 3,
    baseEnvironment: {
      habitat: '林下灌丛、树根洞穴与森林边缘',
      climate: '撞击后寒冷灰暗，随后逐渐回暖',
      suitability: 55,
      threats: ['残存大型爬行掠食者', '火山灰与饥荒', '寒冷长夜', '巢穴竞争'],
      opportunities: ['夜行避敌', '杂食开拓', '育幼提高存活率', '空洞生态位'],
      nearbyLife: ['小型恐龙/鸟类残留', '昆虫爆发', '早期显花植物', '同类小型哺乳'],
      notes: '体型宜小、行为宜灵活；蛮力不是这个纪元的最优解。',
    },
    choices: [
      {
        id: 'nocturnal',
        text: '彻底夜行，避开大型猎手',
        enterEvents: true,
        gainTrait: '夜视嗅觉',
        fitnessDelta: 6,
      },
      {
        id: 'scavenge',
        text: '白天翻找大型尸体',
        dangerHint: '可能撞上仍存活的掠食者',
        successRate: 0.55,
        enterEvents: true,
        gainTrait: '食腐开拓',
        fitnessDelta: 7,
        failText: '腐肉旁的阴影扑来，你成了下一道菜。',
      },
      {
        id: 'arboreal',
        text: '上树筑巢，远离地面',
        enterEvents: true,
        gainTrait: '树栖抓握',
        fitnessDelta: 5,
      },
      {
        id: 'social',
        text: '小群协作育幼与警戒',
        enterEvents: true,
        gainTrait: '社群育幼',
        fitnessDelta: 6,
      },
    ],
  },
  {
    id: 'primate',
    label: '新生代 · 灵长',
    yearLabel: '约 2500 万年前',
    yearMa: 25,
    form: '早期猿类 / 高等灵长类',
    milestoneTitle: '树冠智慧',
    milestoneText:
      '【固有进化】对握拇指、立体视觉与更复杂的社群出现了。森林是课堂，也是战场。\n\n工具还只是一根偶然的细枝——但模仿已经开始。',
    eventsBeforeNext: 3,
    baseEnvironment: {
      habitat: '热带—亚热带森林树冠与林缘',
      climate: '总体温暖，后期草原开始扩张',
      suitability: 63,
      threats: ['大型猫科/猛禽', '坠落', '毒虫', '栖息地碎片化'],
      opportunities: ['果实季节记忆', '工具雏形', '警报叫声', '联盟理毛'],
      nearbyLife: ['古猿与猴类', '早期象类/偶蹄类', '蛇类', '丰富鸟类与昆虫'],
      notes: '大脑与社会关系开始比獠牙更重要。',
    },
    choices: [
      {
        id: 'fruit',
        text: '专精采果，强化色彩与记忆',
        enterEvents: true,
        gainTrait: '果食记忆',
        fitnessDelta: 5,
      },
      {
        id: 'tool',
        text: '用细枝钓取昆虫',
        dangerHint: '毒虫与坠落风险',
        successRate: 0.6,
        enterEvents: true,
        gainTrait: '初级工具',
        fitnessDelta: 9,
        failText: '树枝断裂，你坠落在林下灌丛中。',
      },
      {
        id: 'signal',
        text: '发展叫声与表情传递信息',
        enterEvents: true,
        gainTrait: '通讯社群',
        fitnessDelta: 6,
      },
      {
        id: 'ground',
        text: '下地翻找块茎',
        dangerHint: '地面掠食者更多',
        successRate: 0.5,
        enterEvents: true,
        gainTrait: '地面觅食',
        fitnessDelta: 7,
        failText: '草丛中的眼睛比果实先找到你。',
      },
    ],
  },
  {
    id: 'human',
    label: '更新世 · 智人',
    yearLabel: '约 30 万年前',
    yearMa: 0.3,
    form: '早期智人',
    milestoneTitle: '直立者与火',
    milestoneText:
      '【固有进化】双足解放双手，石器与火塘改写夜晚。你开始讲述不在场的事物——想象诞生了。\n\n冰期的风已经在远方蓄势。',
    eventsBeforeNext: 3,
    baseEnvironment: {
      habitat: '稀树草原、河岸廊道与岩厦洞穴',
      climate: '冰期—间冰期剧烈波动',
      suitability: 57,
      threats: ['剑齿虎等猛兽', '食物短缺', '族群冲突', '严寒风暴'],
      opportunities: ['火与熟食', '协作围猎', '远距离迁徙', '象征与绘画'],
      nearbyLife: ['大型食草动物', '其他古人类族群', '猛禽', '可食块茎与浆果'],
      notes: '文化传递开始加速，个体经验可以变成族群知识。',
    },
    choices: [
      {
        id: 'fire',
        text: '守护火种，发展熟食',
        enterEvents: true,
        gainTrait: '用火',
        fitnessDelta: 8,
      },
      {
        id: 'hunt',
        text: '组织围猎巨型猎物',
        dangerHint: '猛兽反杀风险极高',
        successRate: 0.5,
        enterEvents: true,
        gainTrait: '协作狩猎',
        fitnessDelta: 9,
        failText: '受伤的巨兽冲破包围，长矛折断在夜色里。',
      },
      {
        id: 'gather',
        text: '精于采集与植物知识',
        enterEvents: true,
        gainTrait: '采集地图',
        fitnessDelta: 6,
      },
      {
        id: 'art',
        text: '在岩壁留下象征图案',
        enterEvents: true,
        gainTrait: '象征思维',
        fitnessDelta: 5,
      },
    ],
  },
  {
    id: 'tribe',
    label: '全新世前夜 · 部落',
    yearLabel: '约 1.2 万年前',
    yearMa: 0.012,
    form: '定居/半定居部族',
    milestoneTitle: '部落成型',
    milestoneText:
      '【固有进化】冰期退却，十余个家庭围着同一堆火。图腾、分工与故事把“我们”从血缘扩成名字。\n\n农业的种子，正在河岸泥土里等待被有意留下。',
    eventsBeforeNext: 3,
    baseEnvironment: {
      habitat: '河岸阶地、湖沼边缘与河谷谷地',
      climate: '转暖湿润，季节性洪水增多',
      suitability: 66,
      threats: ['洪水', '饥荒', '部落仇杀', '疫病'],
      opportunities: ['野生谷物', '陶器与储存', '联盟通婚', '驯化萌芽'],
      nearbyLife: ['野牛/鹿类', '鱼类贝类', '野犬狼', '可驯化的草本植物'],
      notes: '自然选择之外，文化选择开始主导命运。',
    },
    choices: [
      {
        id: 'settle',
        text: '河岸定居，尝试栽培',
        enterEvents: true,
        gainTrait: '定居农耕萌芽',
        fitnessDelta: 7,
      },
      {
        id: 'raid',
        text: '袭击邻族抢夺资源',
        dangerHint: '可能引发复仇血战',
        successRate: 0.5,
        enterEvents: true,
        gainTrait: '武力扩张',
        fitnessDelta: 4,
        failText: '夜袭招来报复，火塘被踩灭。',
      },
      {
        id: 'ally',
        text: '与邻族结盟互通婚姻',
        enterEvents: true,
        gainTrait: '同盟网络',
        fitnessDelta: 8,
      },
      {
        id: 'nomad',
        text: '保持游牧，追随兽群',
        enterEvents: true,
        gainTrait: '游牧机动',
        fitnessDelta: 5,
      },
    ],
  },
];

export const eraMap = new Map(eras.map((e) => [e.id, e]));

export function getEra(id: StageId): EraDef {
  const era = eraMap.get(id);
  if (!era) throw new Error(`未知纪元: ${id}`);
  return era;
}

export function nextEraId(id: StageId): StageId | 'ending' {
  const idx = STAGE_ORDER.indexOf(id);
  if (idx < 0 || idx >= STAGE_ORDER.length - 1) return 'ending';
  const next = STAGE_ORDER[idx + 1];
  return next === 'ending' ? 'ending' : next;
}

export function formatYearLabel(yearMa: number): string {
  if (yearMa >= 1000) return `约 ${(yearMa / 1000).toFixed(1)} 亿年前`;
  if (yearMa >= 1) return `约 ${Math.round(yearMa)} 百万年前`;
  if (yearMa >= 0.001) return `约 ${Math.round(yearMa * 10000) / 10} 万年前`;
  return '近现代前夜';
}
