import type {
  ArtDef,
  BranchId,
  EndingDef,
  RealmDef,
  StoryEventDef,
} from './types';

export const MAX_OFFLINE_MS = 8 * 60 * 60 * 1000;
/** 每点气运 +8% 全产出 */
export const QIYUN_BONUS_PER = 0.08;
export const SAVE_VERSION = 1;
export const STORAGE_KEY = 'xian-save-v1';
export const MAX_STAR = 9;
export const MAX_CHRONICLE = 24;

/**
 * 斗破苍穹式境界线：斗之气 → 斗帝
 * 每境九星，九星后破境。
 */
export const REALMS: RealmDef[] = [
  {
    id: 'qi',
    name: '斗之气',
    mult: 1,
    starCostBase: 40,
    breakCost: 800,
    blurb: '气感初开，经脉如细线，每一次吐纳都在拓印根基。',
    hue: 38,
  },
  {
    id: 'zhe',
    name: '斗者',
    mult: 1.8,
    starCostBase: 220,
    breakCost: 6_000,
    blurb: '斗气凝成薄雾，可勉强催动低级斗技。',
    hue: 32,
  },
  {
    id: 'shi',
    name: '斗师',
    mult: 3.2,
    starCostBase: 1_200,
    breakCost: 4e4,
    blurb: '气海成形，道途抉择将在此分岔。',
    hue: 28,
  },
  {
    id: 'dashi',
    name: '大斗师',
    mult: 5.5,
    starCostBase: 7_000,
    breakCost: 2.5e5,
    blurb: '斗气化翼之兆初现，宗门开始留意你的名字。',
    hue: 22,
  },
  {
    id: 'ling',
    name: '斗灵',
    mult: 9.5,
    starCostBase: 4e4,
    breakCost: 1.6e6,
    blurb: '斗气化羽，灵域可覆十丈，天地灵气主动汇聚。',
    hue: 18,
  },
  {
    id: 'wang',
    name: '斗王',
    mult: 16,
    starCostBase: 2.2e5,
    breakCost: 1e7,
    blurb: '一域之王，气机可压城。黑角域与正道皆在招揽。',
    hue: 12,
  },
  {
    id: 'huang',
    name: '斗皇',
    mult: 28,
    starCostBase: 1.2e6,
    breakCost: 6e7,
    blurb: '皇威初显，阵营站队决定你日后的敌人与盟友。',
    hue: 8,
  },
  {
    id: 'zong',
    name: '斗宗',
    mult: 48,
    starCostBase: 7e6,
    breakCost: 3.5e8,
    blurb: '空间之力可撕开裂隙，宗主之位已在脚下。',
    hue: 350,
  },
  {
    id: 'zun',
    name: '斗尊',
    mult: 85,
    starCostBase: 4e7,
    breakCost: 2e9,
    blurb: '尊者一怒，山河变色。气运抉择关乎成帝之路。',
    hue: 330,
  },
  {
    id: 'bansheng',
    name: '半圣',
    mult: 150,
    starCostBase: 2.2e8,
    breakCost: 1.2e10,
    blurb: '半只脚踏入圣境，天劫隐隐作响。',
    hue: 280,
  },
  {
    id: 'sheng',
    name: '斗圣',
    mult: 280,
    starCostBase: 1.2e9,
    breakCost: 8e10,
    blurb: '圣威如渊，一念可灭国。斗帝之门在云端半开。',
    hue: 200,
  },
  {
    id: 'di',
    name: '斗帝',
    mult: 500,
    starCostBase: 8e9,
    breakCost: 0,
    blurb: '帝位临世，天道侧目。此境之上，唯余传说。',
    hue: 45,
  },
];

export const BRANCH_LABELS: Record<BranchId, { name: string; blurb: string; mult: number }> = {
  flame: {
    name: '焚炎道途',
    blurb: '以异火炼体炼魂，焚尽拦路之物。',
    mult: 1.12,
  },
  alchemy: {
    name: '炼药道途',
    blurb: '丹香入骨，以药力补先天之缺。',
    mult: 1.1,
  },
  body: {
    name: '霸体道途',
    blurb: '肉身成圣，拳可崩山，不借外物。',
    mult: 1.15,
  },
  soul: {
    name: '魂噬道途',
    blurb: '以灵魂为刃，诡异难测，亦易入魔。',
    mult: 1.14,
  },
  beast: {
    name: '兽契道途',
    blurb: '与魔兽心意相通，万兽可为羽翼。',
    mult: 1.11,
  },
  sword: {
    name: '剑心道途',
    blurb: '一剑破万法，斗技凝成剑意。',
    mult: 1.13,
  },
};

/** 通用 + 分支功法（体量较大） */
export const ARTS: ArtDef[] = [
  // —— 通用吐纳 ——
  {
    id: 'tuna_basic',
    name: '基础吐纳',
    description: '每次吐纳吸入更多斗气。',
    kind: 'click',
    baseCost: 15,
    costMult: 1.13,
    power: 0.6,
    minRealm: 0,
    mark: '纳',
  },
  {
    id: 'meridian_open',
    name: '洗经伐脉',
    description: '疏通经脉，点击吸气更猛。',
    kind: 'click',
    baseCost: 140,
    costMult: 1.15,
    power: 2.2,
    minRealm: 0,
    mark: '脉',
  },
  {
    id: 'qi_vortex',
    name: '气旋吞吐',
    description: '气海成涡，一吸千缕。',
    kind: 'click',
    baseCost: 1_200,
    costMult: 1.16,
    power: 9,
    minRealm: 1,
    mark: '涡',
  },
  {
    id: 'dragon_breath',
    name: '龙息吐纳',
    description: '仿龙族呼吸，点击力暴涨。',
    kind: 'click',
    baseCost: 1.2e4,
    costMult: 1.17,
    power: 35,
    minRealm: 3,
    mark: '龙',
  },
  {
    id: 'heaven_draw',
    name: '抽天夺气',
    description: '强行抽取天地灵气，凶险却极快。',
    kind: 'click',
    baseCost: 1.5e5,
    costMult: 1.18,
    power: 140,
    minRealm: 5,
    mark: '夺',
  },
  {
    id: 'emperor_inhale',
    name: '帝息一缕',
    description: '模拟斗帝呼吸节奏，点击如潮。',
    kind: 'click',
    baseCost: 3e6,
    costMult: 1.2,
    power: 600,
    minRealm: 8,
    mark: '帝',
  },

  // —— 通用运转 ——
  {
    id: 'sit_meditation',
    name: '静室打坐',
    description: '每秒缓慢积攒斗气。',
    kind: 'passive',
    baseCost: 50,
    costMult: 1.12,
    power: 0.4,
    minRealm: 0,
    mark: '坐',
  },
  {
    id: 'spirit_gather',
    name: '聚灵阵纹',
    description: '在洞府刻画聚灵，被动提升。',
    kind: 'passive',
    baseCost: 400,
    costMult: 1.14,
    power: 2,
    minRealm: 1,
    mark: '阵',
  },
  {
    id: 'cave_mansion',
    name: '洞府灵脉',
    description: '占据一处灵脉，日夜滋养。',
    kind: 'passive',
    baseCost: 4_000,
    costMult: 1.15,
    power: 10,
    minRealm: 2,
    mark: '府',
  },
  {
    id: 'sect_salary',
    name: '宗门俸禄',
    description: '挂名宗门，月例化为斗气。',
    kind: 'passive',
    baseCost: 3e4,
    costMult: 1.16,
    power: 45,
    minRealm: 3,
    mark: '俸',
  },
  {
    id: 'domain_tax',
    name: '领地气税',
    description: '以势压人，领地灵气上供。',
    kind: 'passive',
    baseCost: 2.5e5,
    costMult: 1.17,
    power: 180,
    minRealm: 5,
    mark: '税',
  },
  {
    id: 'void_well',
    name: '虚空井',
    description: '连通虚空，源源不断。',
    kind: 'passive',
    baseCost: 4e6,
    costMult: 1.18,
    power: 800,
    minRealm: 7,
    mark: '井',
  },
  {
    id: 'heaven_vein',
    name: '天脉共鸣',
    description: '与大陆天脉共鸣，被动如瀑。',
    kind: 'passive',
    baseCost: 6e7,
    costMult: 1.2,
    power: 3500,
    minRealm: 9,
    mark: '天',
  },

  // —— 焚炎 ——
  {
    id: 'flame_seed',
    name: '火种温养',
    description: '掌心温养一枚火种，助推吐纳。',
    kind: 'click',
    baseCost: 3_000,
    costMult: 1.16,
    power: 18,
    minRealm: 2,
    branch: 'flame',
    mark: '火',
  },
  {
    id: 'beast_flame',
    name: '兽火炼体',
    description: '以兽火淬体，被动灼烧杂质。',
    kind: 'passive',
    baseCost: 8_000,
    costMult: 1.15,
    power: 22,
    minRealm: 3,
    branch: 'flame',
    mark: '兽',
  },
  {
    id: 'strange_fire',
    name: '异火残种',
    description: '寻得异火残种，焚尽阻碍。',
    kind: 'passive',
    baseCost: 2e5,
    costMult: 1.17,
    power: 120,
    minRealm: 5,
    branch: 'flame',
    mark: '异',
  },
  {
    id: 'flame_lotus',
    name: '三千焱炎',
    description: '火莲绽放，点击与被动皆盛。',
    kind: 'click',
    baseCost: 5e6,
    costMult: 1.19,
    power: 900,
    minRealm: 7,
    branch: 'flame',
    mark: '莲',
  },
  {
    id: 'emperor_flame',
    name: '帝炎虚影',
    description: '模拟帝级异火虚影，被动焚天。',
    kind: 'passive',
    baseCost: 8e7,
    costMult: 1.21,
    power: 4200,
    minRealm: 9,
    branch: 'flame',
    mark: '炎',
  },

  // —— 炼药 ——
  {
    id: 'herb_pick',
    name: '识药辨草',
    description: '采药入鼎，点击炼化药力。',
    kind: 'click',
    baseCost: 2_800,
    costMult: 1.15,
    power: 16,
    minRealm: 2,
    branch: 'alchemy',
    mark: '药',
  },
  {
    id: 'cauldron',
    name: '青铜丹炉',
    description: '丹炉常燃，被动出丹。',
    kind: 'passive',
    baseCost: 9_000,
    costMult: 1.15,
    power: 24,
    minRealm: 3,
    branch: 'alchemy',
    mark: '炉',
  },
  {
    id: 'soul_flame_refine',
    name: '魂火炼药',
    description: '以灵魂之火控丹，成丹率大增。',
    kind: 'passive',
    baseCost: 2.2e5,
    costMult: 1.17,
    power: 130,
    minRealm: 5,
    branch: 'alchemy',
    mark: '魂',
  },
  {
    id: 'tier8_pill',
    name: '八品丹方',
    description: '八品丹药入腹，吐纳如虹。',
    kind: 'click',
    baseCost: 4e6,
    costMult: 1.18,
    power: 850,
    minRealm: 7,
    branch: 'alchemy',
    mark: '八',
  },
  {
    id: 'pill_tower',
    name: '丹塔传承',
    description: '丹塔古籍加持，被动绵长。',
    kind: 'passive',
    baseCost: 7e7,
    costMult: 1.2,
    power: 4000,
    minRealm: 9,
    branch: 'alchemy',
    mark: '塔',
  },

  // —— 霸体 ——
  {
    id: 'bone_temper',
    name: '锻骨淬筋',
    description: '以力破巧，点击更刚猛。',
    kind: 'click',
    baseCost: 3_200,
    costMult: 1.16,
    power: 20,
    minRealm: 2,
    branch: 'body',
    mark: '骨',
  },
  {
    id: 'blood_boil',
    name: '血气如潮',
    description: '气血翻涌，被动不息。',
    kind: 'passive',
    baseCost: 1e4,
    costMult: 1.15,
    power: 26,
    minRealm: 3,
    branch: 'body',
    mark: '血',
  },
  {
    id: 'diamond_body',
    name: '金刚不坏',
    description: '肉身硬抗斗技，根基深厚。',
    kind: 'passive',
    baseCost: 2.8e5,
    costMult: 1.17,
    power: 145,
    minRealm: 5,
    branch: 'body',
    mark: '金',
  },
  {
    id: 'titan_fist',
    name: '开山拳意',
    description: '一拳崩山，点击爆发。',
    kind: 'click',
    baseCost: 5.5e6,
    costMult: 1.19,
    power: 980,
    minRealm: 7,
    branch: 'body',
    mark: '拳',
  },
  {
    id: 'immortal_flesh',
    name: '不灭霸体',
    description: '肉身近圣，被动如山岳。',
    kind: 'passive',
    baseCost: 9e7,
    costMult: 1.21,
    power: 4500,
    minRealm: 9,
    branch: 'body',
    mark: '霸',
  },

  // —— 魂噬 ——
  {
    id: 'soul_sense',
    name: '灵魂感知',
    description: '以神识搜刮游离斗气。',
    kind: 'click',
    baseCost: 3_100,
    costMult: 1.16,
    power: 19,
    minRealm: 2,
    branch: 'soul',
    mark: '识',
  },
  {
    id: 'soul_devour',
    name: '噬魂残诀',
    description: '吞噬残魂，被动阴冷增长。',
    kind: 'passive',
    baseCost: 9_500,
    costMult: 1.16,
    power: 25,
    minRealm: 3,
    branch: 'soul',
    mark: '噬',
  },
  {
    id: 'soul_palace',
    name: '灵魂殿堂',
    description: '筑灵魂殿，稳固神识。',
    kind: 'passive',
    baseCost: 2.6e5,
    costMult: 1.17,
    power: 135,
    minRealm: 5,
    branch: 'soul',
    mark: '殿',
  },
  {
    id: 'soul_storm',
    name: '灵魂风暴',
    description: '神识化风暴，点击席卷。',
    kind: 'click',
    baseCost: 5.2e6,
    costMult: 1.19,
    power: 920,
    minRealm: 7,
    branch: 'soul',
    mark: '暴',
  },
  {
    id: 'heaven_soul',
    name: '天魂残卷',
    description: '沾染天魂之力，被动诡谲。',
    kind: 'passive',
    baseCost: 8.5e7,
    costMult: 1.21,
    power: 4300,
    minRealm: 9,
    branch: 'soul',
    mark: '天',
  },

  // —— 兽契 ——
  {
    id: 'beast_whisper',
    name: '兽语低语',
    description: '与低阶魔兽沟通，得其灵息。',
    kind: 'click',
    baseCost: 2_900,
    costMult: 1.15,
    power: 17,
    minRealm: 2,
    branch: 'beast',
    mark: '语',
  },
  {
    id: 'contract_pup',
    name: '契约幼兽',
    description: '签下第一份契约，被动共享血脉。',
    kind: 'passive',
    baseCost: 8_500,
    costMult: 1.15,
    power: 23,
    minRealm: 3,
    branch: 'beast',
    mark: '契',
  },
  {
    id: 'winged_mount',
    name: '翼兽坐骑',
    description: '天空亦是猎场，被动加速。',
    kind: 'passive',
    baseCost: 2.4e5,
    costMult: 1.17,
    power: 125,
    minRealm: 5,
    branch: 'beast',
    mark: '翼',
  },
  {
    id: 'ancient_blood',
    name: '古兽精血',
    description: '饮古兽精血，点击狂暴。',
    kind: 'click',
    baseCost: 4.8e6,
    costMult: 1.18,
    power: 880,
    minRealm: 7,
    branch: 'beast',
    mark: '血',
  },
  {
    id: 'beast_king_crown',
    name: '万兽朝拜',
    description: '兽潮听令，被动如林海。',
    kind: 'passive',
    baseCost: 7.5e7,
    costMult: 1.2,
    power: 4100,
    minRealm: 9,
    branch: 'beast',
    mark: '王',
  },

  // —— 剑心 ——
  {
    id: 'sword_basic',
    name: '基础剑式',
    description: '以剑意引气，吐纳更锋。',
    kind: 'click',
    baseCost: 3_000,
    costMult: 1.16,
    power: 18,
    minRealm: 2,
    branch: 'sword',
    mark: '式',
  },
  {
    id: 'sword_domain',
    name: '剑域雏形',
    description: '寸许剑域，被动削铁。',
    kind: 'passive',
    baseCost: 9_200,
    costMult: 1.15,
    power: 24,
    minRealm: 3,
    branch: 'sword',
    mark: '域',
  },
  {
    id: 'flying_sword',
    name: '御剑千里',
    description: '飞剑巡空，搜罗灵气。',
    kind: 'passive',
    baseCost: 2.5e5,
    costMult: 1.17,
    power: 128,
    minRealm: 5,
    branch: 'sword',
    mark: '御',
  },
  {
    id: 'sword_heart',
    name: '剑心通明',
    description: '心剑合一，点击破妄。',
    kind: 'click',
    baseCost: 5e6,
    costMult: 1.19,
    power: 910,
    minRealm: 7,
    branch: 'sword',
    mark: '心',
  },
  {
    id: 'heaven_slash',
    name: '开天一剑',
    description: '剑意问天，被动裂空。',
    kind: 'passive',
    baseCost: 8e7,
    costMult: 1.21,
    power: 4400,
    minRealm: 9,
    branch: 'sword',
    mark: '开',
  },

  // —— 阵营专属 ——
  {
    id: 'orthodox_edict',
    name: '正道敕令',
    description: '正道资源倾斜，被动丰厚。',
    kind: 'passive',
    baseCost: 8e5,
    costMult: 1.16,
    power: 220,
    minRealm: 6,
    faction: 'orthodox',
    mark: '正',
  },
  {
    id: 'dark_plunder',
    name: '黑角掠夺',
    description: '以掠夺换资源，点击凶狠。',
    kind: 'click',
    baseCost: 7e5,
    costMult: 1.17,
    power: 260,
    minRealm: 6,
    faction: 'dark',
    mark: '黑',
  },
  {
    id: 'hermit_quiet',
    name: '隐世清修',
    description: '不问世事，打坐效率奇高。',
    kind: 'passive',
    baseCost: 7.5e5,
    costMult: 1.16,
    power: 240,
    minRealm: 6,
    faction: 'hermit',
    mark: '隐',
  },
];

export const STORY_EVENTS: StoryEventDef[] = [
  {
    id: 'choose_branch',
    title: '道途分岔',
    body: '斗师中期，你感应到六条截然不同的气机。选错可再轮回，但此世只能执一条道途走到底。',
    minRealm: 2,
    minStar: 3,
    options: [
      {
        id: 'pick_flame',
        label: '焚炎',
        blurb: BRANCH_LABELS.flame.blurb,
        set: { branchId: 'flame' },
        flags: ['path_flame'],
      },
      {
        id: 'pick_alchemy',
        label: '炼药',
        blurb: BRANCH_LABELS.alchemy.blurb,
        set: { branchId: 'alchemy' },
        flags: ['path_alchemy'],
      },
      {
        id: 'pick_body',
        label: '霸体',
        blurb: BRANCH_LABELS.body.blurb,
        set: { branchId: 'body' },
        flags: ['path_body'],
      },
      {
        id: 'pick_soul',
        label: '魂噬',
        blurb: BRANCH_LABELS.soul.blurb,
        set: { branchId: 'soul' },
        flags: ['path_soul'],
      },
      {
        id: 'pick_beast',
        label: '兽契',
        blurb: BRANCH_LABELS.beast.blurb,
        set: { branchId: 'beast' },
        flags: ['path_beast'],
      },
      {
        id: 'pick_sword',
        label: '剑心',
        blurb: BRANCH_LABELS.sword.blurb,
        set: { branchId: 'sword' },
        flags: ['path_sword'],
      },
    ],
  },
  {
    id: 'flame_trial',
    title: '火山试炼',
    body: '地底岩浆涌动，一缕异火残息扑面而来。是强行吞纳，还是稳妥温养？',
    minRealm: 4,
    requireBranch: 'flame',
    options: [
      {
        id: 'flame_swallow',
        label: '强行吞纳',
        blurb: '险中求胜，获「异火亲和」。',
        flags: ['strange_fire_affinity'],
        douqiDelta: -5e4,
        qiyunDelta: 1,
      },
      {
        id: 'flame_nurture',
        label: '稳妥温养',
        blurb: '根基更稳，获「火莲苗」。',
        flags: ['fire_lotus_seed'],
        douqiDelta: 2e4,
      },
    ],
  },
  {
    id: 'alchemy_auction',
    title: '黑市丹拍',
    body: '黑市出现一份残缺八品丹方。争抢者众，你如何取舍？',
    minRealm: 4,
    requireBranch: 'alchemy',
    options: [
      {
        id: 'alchemy_bid',
        label: '倾囊竞拍',
        blurb: '换得丹方，丹塔日后或认你。',
        flags: ['pill_formula', 'dantower_favor'],
        douqiDelta: -8e4,
      },
      {
        id: 'alchemy_steal',
        label: '神识窃取',
        blurb: '记下半卷，却染上「盗方」之名。',
        flags: ['pill_formula', 'thief_name'],
        douqiDelta: -1e4,
      },
    ],
  },
  {
    id: 'body_arena',
    title: '角斗场',
    body: '有人以重金请你下场硬碰。赢则扬名，输则伤筋。',
    minRealm: 4,
    requireBranch: 'body',
    options: [
      {
        id: 'body_fight',
        label: '下场硬碰',
        blurb: '打出名号「不灭」。',
        flags: ['undying_title'],
        douqiDelta: 3e4,
        qiyunDelta: 1,
      },
      {
        id: 'body_refuse',
        label: '拒而不战',
        blurb: '潜心锻体，获「静修」。',
        flags: ['quiet_temper'],
        douqiDelta: 5e4,
      },
    ],
  },
  {
    id: 'soul_whisper',
    title: '骨骸低语',
    body: '荒野骨堆中有残魂求你带走。它许以秘法，也带着怨毒。',
    minRealm: 4,
    requireBranch: 'soul',
    options: [
      {
        id: 'soul_accept',
        label: '收纳残魂',
        blurb: '得「天魂线索」，亦沾「怨毒」。',
        flags: ['heaven_soul_clue', 'resentment'],
        qiyunDelta: 1,
      },
      {
        id: 'soul_seal',
        label: '镇压超度',
        blurb: '心境清明，获「净魂」。',
        flags: ['pure_soul'],
        douqiDelta: 2e4,
      },
    ],
  },
  {
    id: 'beast_egg',
    title: '古兽蛋',
    body: '你在山谷发现一枚温热的兽蛋，壳上古纹流动。',
    minRealm: 4,
    requireBranch: 'beast',
    options: [
      {
        id: 'beast_hatch',
        label: '以血孵化',
        blurb: '结下生死契，获「古兽伴」。',
        flags: ['ancient_companion'],
        douqiDelta: -3e4,
        qiyunDelta: 1,
      },
      {
        id: 'beast_sell',
        label: '卖予商会',
        blurb: '换来海量资源，却失机缘。',
        flags: ['sold_destiny'],
        douqiDelta: 1.2e5,
      },
    ],
  },
  {
    id: 'sword_grave',
    title: '剑冢一夜',
    body: '万剑嗡鸣，一座古剑主动飞起，悬于你眉心。',
    minRealm: 4,
    requireBranch: 'sword',
    options: [
      {
        id: 'sword_bond',
        label: '以心认剑',
        blurb: '剑意入体，获「心剑」。',
        flags: ['heart_sword'],
        douqiDelta: -2e4,
        qiyunDelta: 1,
      },
      {
        id: 'sword_leave',
        label: '一拜离去',
        blurb: '不贪不执，获「空明」。',
        flags: ['sword_empty'],
        douqiDelta: 4e4,
      },
    ],
  },
  {
    id: 'choose_faction',
    title: '阵营招揽',
    body: '斗皇之境，三方使者同日至府：正道联盟、黑角域、以及一位不留名的隐者。',
    minRealm: 6,
    minStar: 1,
    options: [
      {
        id: 'fac_orthodox',
        label: '加入正道',
        blurb: '资源与名声，也有枷锁。',
        set: { factionId: 'orthodox' },
        flags: ['faction_orthodox'],
        douqiDelta: 5e5,
      },
      {
        id: 'fac_dark',
        label: '投向黑角',
        blurb: '自由与血腥并存。',
        set: { factionId: 'dark' },
        flags: ['faction_dark'],
        douqiDelta: 8e5,
        qiyunDelta: -1,
      },
      {
        id: 'fac_hermit',
        label: '隐世散修',
        blurb: '无人搅扰，亦无人援手。',
        set: { factionId: 'hermit' },
        flags: ['faction_hermit'],
        qiyunDelta: 2,
      },
    ],
  },
  {
    id: 'dark_massacre',
    title: '血夜',
    body: '黑角域命你屠一座拒贡的城。拒则被追杀，从则双手染血。',
    minRealm: 7,
    requireFaction: 'dark',
    options: [
      {
        id: 'dark_kill',
        label: '血洗全城',
        blurb: '魔名远扬，获「魔君雏形」。',
        flags: ['demon_lord_seed', 'blood_hands'],
        douqiDelta: 2e6,
      },
      {
        id: 'dark_fake',
        label: '假报军情',
        blurb: '暗中放人，获「双面」。',
        flags: ['double_face'],
        douqiDelta: -5e5,
        qiyunDelta: 1,
      },
    ],
  },
  {
    id: 'orthodox_trial',
    title: '正道大比',
    body: '联盟举办大比，邀你压阵。是显露锋芒，还是藏拙？',
    minRealm: 7,
    requireFaction: 'orthodox',
    options: [
      {
        id: 'ortho_win',
        label: '全力夺魁',
        blurb: '正道领袖之位相露。',
        flags: ['alliance_leader'],
        douqiDelta: 1e6,
        qiyunDelta: 1,
      },
      {
        id: 'ortho_hide',
        label: '点到为止',
        blurb: '少树敌，获「稳重」。',
        flags: ['steady_name'],
        douqiDelta: 4e5,
      },
    ],
  },
  {
    id: 'choose_destiny',
    title: '气运抉择',
    body: '斗尊巅峰，天道降下三道气机：成帝、守界、或问虚空。',
    minRealm: 8,
    minStar: 5,
    options: [
      {
        id: 'des_emperor',
        label: '执意成帝',
        blurb: '以气运赌那一线帝位。',
        set: { destinyId: 'emperor' },
        flags: ['destiny_emperor'],
        qiyunDelta: -2,
      },
      {
        id: 'des_guardian',
        label: '镇守大陆',
        blurb: '护一方生灵，成守护者。',
        set: { destinyId: 'guardian' },
        flags: ['destiny_guardian'],
        qiyunDelta: 3,
      },
      {
        id: 'des_void',
        label: '问道虚空',
        blurb: '抛下大陆，追逐更高未知。',
        set: { destinyId: 'void' },
        flags: ['destiny_void'],
        douqiDelta: 5e7,
      },
    ],
  },
  {
    id: 'heaven_tribulation',
    title: '天劫将至',
    body: '半圣关口，九色雷云压顶。是硬抗，借阵，还是以他人挡灾？',
    minRealm: 9,
    minStar: 2,
    options: [
      {
        id: 'trib_hard',
        label: '肉身硬抗',
        blurb: '若活，则「劫后余生」。',
        flags: ['survived_tribulation'],
        douqiDelta: -2e8,
        qiyunDelta: 2,
      },
      {
        id: 'trib_array',
        label: '借聚灵阵',
        blurb: '稳妥渡劫，获「阵法渡劫」。',
        flags: ['array_tribulation'],
        douqiDelta: -5e7,
      },
      {
        id: 'trib_sacrifice',
        label: '移花接木',
        blurb: '灾移他人，获「因果债」。',
        flags: ['karmic_debt', 'blood_hands'],
        douqiDelta: 1e8,
        qiyunDelta: -3,
      },
    ],
  },
  {
    id: 'final_gate',
    title: '帝门半开',
    body: '斗圣巅峰，一道帝门虚影现于云端。跨入与否，决定此世收束。',
    minRealm: 10,
    minStar: 8,
    options: [
      {
        id: 'gate_enter',
        label: '踏入帝门',
        blurb: '赌那成帝一线。',
        flags: ['entered_emperor_gate'],
        douqiDelta: -1e10,
      },
      {
        id: 'gate_wait',
        label: '暂且观望',
        blurb: '再积气运，获「隐忍」。',
        flags: ['patient_wait'],
        qiyunDelta: 2,
      },
    ],
  },
];

export const ENDINGS: EndingDef[] = [
  {
    id: 'yan_di',
    name: '炎帝转世',
    title: '异火归位，炎帝之名重临',
    body: '你以焚炎道途走通帝境，异火亲和与帝炎虚影共鸣，大陆只记得那一团不灭的火光。',
    priority: 100,
    minRealm: 11,
    requireBranch: 'flame',
    requireFlags: ['strange_fire_affinity', 'entered_emperor_gate'],
    requireArts: { emperor_flame: 1 },
  },
  {
    id: 'pill_sovereign',
    name: '药尊无上',
    title: '丹香覆陆，药尊登临',
    body: '丹塔传承在你掌中续写。八品之上，丹成而帝成。',
    priority: 95,
    minRealm: 11,
    requireBranch: 'alchemy',
    requireFlags: ['dantower_favor', 'pill_formula'],
    requireArts: { pill_tower: 1 },
  },
  {
    id: 'undying_body',
    name: '不灭霸体',
    title: '肉身成帝，拳碎天劫',
    body: '你未借外火外丹，仅以筋骨血气撞开帝门。山河记住了那一拳。',
    priority: 95,
    minRealm: 11,
    requireBranch: 'body',
    requireFlags: ['undying_title', 'survived_tribulation'],
    requireArts: { immortal_flesh: 1 },
  },
  {
    id: 'soul_heaven',
    name: '魂天帝影',
    title: '灵魂覆天，帝影如魅',
    body: '天魂残卷展开，你与那道古老意志短暂重叠。世人称你为魂天。',
    priority: 95,
    minRealm: 11,
    requireBranch: 'soul',
    requireFlags: ['heaven_soul_clue', 'entered_emperor_gate'],
    requireArts: { heaven_soul: 1 },
  },
  {
    id: 'beast_sovereign',
    name: '万兽共主',
    title: '兽潮听令，共主临世',
    body: '古兽伴你左右，万兽低伏。帝位之上，你更像一位兽原的王。',
    priority: 95,
    minRealm: 11,
    requireBranch: 'beast',
    requireFlags: ['ancient_companion'],
    requireArts: { beast_king_crown: 1 },
  },
  {
    id: 'sword_heaven',
    name: '剑开天门',
    title: '一剑问天，门开帝落',
    body: '心剑出鞘，天门为你而裂。剑意即帝意。',
    priority: 95,
    minRealm: 11,
    requireBranch: 'sword',
    requireFlags: ['heart_sword', 'entered_emperor_gate'],
    requireArts: { heaven_slash: 1 },
  },
  {
    id: 'demon_lord',
    name: '魔君临世',
    title: '黑角升起，魔君覆城',
    body: '血夜之后再无回头路。你以黑角之力踏入帝境，大陆战栗。',
    priority: 90,
    minRealm: 11,
    requireFaction: 'dark',
    requireFlags: ['demon_lord_seed', 'blood_hands'],
  },
  {
    id: 'alliance_king',
    name: '正道盟主',
    title: '敕令天下，盟主镇世',
    body: '正道大旗在你身后展开。帝位是权柄，也是枷锁。',
    priority: 88,
    minRealm: 11,
    requireFaction: 'orthodox',
    requireFlags: ['alliance_leader'],
    requireDestiny: 'guardian',
  },
  {
    id: 'void_wanderer',
    name: '虚空行者',
    title: '弃陆问虚，行踪无定',
    body: '你未坐帝座，却走进了更深的虚空。有人说你成了，有人说你消散了。',
    priority: 88,
    minRealm: 10,
    requireDestiny: 'void',
    requireFlags: ['destiny_void'],
  },
  {
    id: 'hermit_immortal',
    name: '逍遥散仙',
    title: '隐世清修，逍遥自在',
    body: '无人知你姓名，只在某座无名峰顶，有人看见帝光一闪即隐。',
    priority: 85,
    minRealm: 11,
    requireFaction: 'hermit',
    requireDestiny: 'guardian',
  },
  {
    id: 'karmic_fall',
    name: '因果陨落',
    title: '债满身灭，帝路崩塌',
    body: '移花接木的天劫终于回来。你在帝门前散作飞灰，只留下一句笑。',
    priority: 120,
    minRealm: 10,
    requireFlags: ['karmic_debt', 'entered_emperor_gate'],
  },
  {
    id: 'patient_emperor',
    name: '隐忍成帝',
    title: '观望千日，一朝登临',
    body: '你未急着踏门，气运堆叠至满，终以最稳的姿态坐下帝座。',
    priority: 80,
    minRealm: 11,
    requireFlags: ['patient_wait'],
    requireDestiny: 'emperor',
    minQiyun: 8,
  },
  {
    id: 'thief_pill',
    name: '盗丹邪尊',
    title: '窃方成道，邪名远播',
    body: '你以盗来的丹方走到巅峰。丹香与恶名一样浓。',
    priority: 70,
    minRealm: 10,
    requireBranch: 'alchemy',
    requireFlags: ['thief_name', 'pill_formula'],
  },
  {
    id: 'default_emperor',
    name: '斗帝登临',
    title: '帝位落座，天道侧目',
    body: '无论道途如何，你终究站上了那座人人仰望的巅峰。此世落幕，轮回可再启。',
    priority: 10,
    minRealm: 11,
  },
  {
    id: 'fallen_wild',
    name: '陨落荒野',
    title: '气散人亡，荒野无名冢',
    body: '轮回之时你几乎一无所获。有人在荒野见过一具枯骨，斗气早已散尽。',
    priority: 5,
    minRealm: 0,
    minQiyun: 0,
  },
];

export function getRealm(index: number): RealmDef {
  return REALMS[Math.max(0, Math.min(REALMS.length - 1, index))]!;
}

export function getArt(id: string): ArtDef | undefined {
  return ARTS.find((a) => a.id === id);
}

export function getEnding(id: string): EndingDef | undefined {
  return ENDINGS.find((e) => e.id === id);
}
