import type {
  ArtDef,
  AttrMap,
  BirthDef,
  BranchId,
  EndingDef,
  EnemyDef,
  RealmDef,
  ResourceKey,
  ResourceMap,
  StoryEventDef,
  TreasureDef,
} from './types';
import {
  BODY_STAGES,
  HERBS,
  PILL_RECIPES,
  bodyAttrsBonus,
  bodyMultipliers,
  emptyHerbs,
  emptyPills,
  getBodyStage,
  getHerb,
  getPillRecipe,
} from './craft';
import { MAIN_STORY, NATURALS, TREASURES, emptyEquipped, getNatural, listEquippedIds, slotCapacity } from './loot';

export {
  MAIN_STORY,
  NATURALS,
  TREASURES,
  emptyEquipped,
  getNatural,
  listEquippedIds,
  slotCapacity,
  BODY_STAGES,
  HERBS,
  PILL_RECIPES,
  bodyAttrsBonus,
  bodyMultipliers,
  emptyHerbs,
  emptyPills,
  getBodyStage,
  getHerb,
  getPillRecipe,
};

export const MAX_OFFLINE_MS = 8 * 60 * 60 * 1000;
export const QIYUN_BONUS_PER = 0.08;
export const SAVE_VERSION = 7;
export const STORAGE_KEY = 'xian-save-v7';
export const MAX_STAR = 9;
export const MAX_CHRONICLE = 28;
export const MAX_MILESTONES = 40;
/** 单类槽位最大格数（随境界逐步解锁） */
export const MAX_EQUIP_PER_SLOT = 3;
/** 旧版 1 自由点折算为各资源量 */
export const FREE_POINT_TO_RESOURCE = 100;
/** 随机奇遇冷却（毫秒） */
export const RANDOM_COOLDOWN_MS = 18_000;
export const RANDOM_CHANCE = {
  click: 0.07,
  level: 0.28,
  time: 0.12,
} as const;

export function zeroAttrs(): AttrMap {
  return { atk: 0, def: 0, spd: 0, spirit: 0, bone: 0, luck: 0 };
}

export function zeroResources(): ResourceMap {
  return { lingli: 0, tishu: 0, jingshen: 0 };
}

/** 功法所属修炼通道 */
export function artChannel(art: ArtDef): ResourceKey {
  if (art.channel) return art.channel;
  if (art.branch === 'body') return 'tishu';
  if (art.branch === 'soul' || art.branch === 'alchemy') return 'jingshen';
  return 'lingli';
}

export function addAttrs(a: AttrMap, b: Partial<AttrMap>): AttrMap {
  return {
    atk: a.atk + (b.atk || 0),
    def: a.def + (b.def || 0),
    spd: a.spd + (b.spd || 0),
    spirit: a.spirit + (b.spirit || 0),
    bone: a.bone + (b.bone || 0),
    luck: a.luck + (b.luck || 0),
  };
}

export function scaleAttrs(a: AttrMap, rate: number): AttrMap {
  return {
    atk: Math.max(0, Math.floor(a.atk * rate)),
    def: Math.max(0, Math.floor(a.def * rate)),
    spd: Math.max(0, Math.floor(a.spd * rate)),
    spirit: Math.max(0, Math.floor(a.spirit * rate)),
    bone: Math.max(0, Math.floor(a.bone * rate)),
    luck: Math.max(0, Math.floor(a.luck * rate)),
  };
}

/**
 * 凡人修仙式境界：炼气 → 真仙
 * 每境九层，满层破境；继承比例随境界提升。
 */
export const REALMS: RealmDef[] = [
  {
    id: 'lianqi',
    name: '炼气',
    mult: 1,
    starCostBase: 35,
    breakCost: 900,
    blurb: '引气入体，凡人迈入仙途第一步。隔壁老王说你命格像开了挂。',
    hue: 42,
    inheritAttrRate: 0.05,
    inheritTreasureSlots: 0,
  },
  {
    id: 'zhuji',
    name: '筑基',
    mult: 1.9,
    starCostBase: 280,
    breakCost: 8_000,
    blurb: '筑基成功，寿元大涨。坊市里开始有人喊你「前辈」。',
    hue: 36,
    inheritAttrRate: 0.12,
    inheritTreasureSlots: 1,
  },
  {
    id: 'jiedan',
    name: '结丹',
    mult: 3.4,
    starCostBase: 1_800,
    breakCost: 5e4,
    blurb: '金丹一道，道途将分。假丹真丹之争，永不过时。',
    hue: 28,
    inheritAttrRate: 0.22,
    inheritTreasureSlots: 1,
  },
  {
    id: 'yuanying',
    name: '元婴',
    mult: 6,
    starCostBase: 1.2e4,
    breakCost: 3.5e5,
    blurb: '元婴出窍，神识可游百里。秘境门票开始对你打折。',
    hue: 18,
    inheritAttrRate: 0.32,
    inheritTreasureSlots: 2,
  },
  {
    id: 'huashen',
    name: '化神',
    mult: 11,
    starCostBase: 7e4,
    breakCost: 2.2e6,
    blurb: '化神合道，天地法则依稀可感。有人喊你「老怪」。',
    hue: 8,
    inheritAttrRate: 0.42,
    inheritTreasureSlots: 2,
  },
  {
    id: 'lianxu',
    name: '炼虚',
    mult: 20,
    starCostBase: 4e5,
    breakCost: 1.4e7,
    blurb: '炼虚合道，空间之力在握。传送阵维修工开始怕你。',
    hue: 350,
    inheritAttrRate: 0.52,
    inheritTreasureSlots: 2,
  },
  {
    id: 'heti',
    name: '合体',
    mult: 36,
    starCostBase: 2.2e6,
    breakCost: 8e7,
    blurb: '合体期，肉身与元神交融。宗门长老见你都要点头。',
    hue: 320,
    inheritAttrRate: 0.62,
    inheritTreasureSlots: 3,
  },
  {
    id: 'dacheng',
    name: '大乘',
    mult: 65,
    starCostBase: 1.2e7,
    breakCost: 5e8,
    blurb: '大乘境，一方雄主。正魔两道都想把你拉进群聊。',
    hue: 280,
    inheritAttrRate: 0.72,
    inheritTreasureSlots: 3,
  },
  {
    id: 'dujie',
    name: '渡劫',
    mult: 120,
    starCostBase: 7e7,
    breakCost: 3e9,
    blurb: '天劫如约而至。这次是雷劫、心魔，还是「系统弹窗」？',
    hue: 200,
    inheritAttrRate: 0.8,
    inheritTreasureSlots: 3,
  },
  {
    id: 'zhenxian',
    name: '真仙',
    mult: 220,
    starCostBase: 4e8,
    breakCost: 2e10,
    blurb: '飞升真仙，灵界户口本盖章。凡人界传说里有你一笔。',
    hue: 160,
    inheritAttrRate: 0.88,
    inheritTreasureSlots: 3,
  },
  {
    id: 'jinxian',
    name: '金仙',
    mult: 400,
    starCostBase: 2.5e9,
    breakCost: 1.2e11,
    blurb: '金仙不灭，法则成河。诸天剧情开始围着你转。',
    hue: 45,
    inheritAttrRate: 0.94,
    inheritTreasureSlots: 3,
  },
  {
    id: 'dadao',
    name: '大道',
    mult: 700,
    starCostBase: 2e10,
    breakCost: 0,
    blurb: '道成，诸天侧目。轮回与否，皆在一念。',
    hue: 30,
    inheritAttrRate: 1,
    inheritTreasureSlots: 3,
  },
];

export const BIRTHS: BirthDef[] = [
  {
    id: 'orphan',
    name: '寒门散修',
    blurb: '破庙出身，口袋比脸干净。好在没人管你，想作死就作死。',
    attrs: { bone: 1, luck: 2, spd: 1 },
    freePoints: 4,
    startLingqi: 0,
    flags: ['birth_orphan'],
    mark: '寒',
  },
  {
    id: 'clan',
    name: '修仙世家',
    blurb: '族谱厚得能拍死妖兽。开局送灵石，也送「族规」debuff。',
    attrs: { spirit: 2, bone: 2, atk: 1 },
    freePoints: 3,
    startLingqi: 80,
    flags: ['birth_clan'],
    mark: '世',
  },
  {
    id: 'sect_outer',
    name: '宗门外门',
    blurb: '扫灵草、喂灵兽、被内门弟子使唤。你发誓有朝一日……先把地扫完。',
    attrs: { def: 2, bone: 1, spirit: 1 },
    freePoints: 3,
    startLingqi: 40,
    flags: ['birth_sect'],
    mark: '外',
  },
  {
    id: 'demon_remnant',
    name: '魔道余脉',
    blurb: '祖上干过大事，现在全家在逃。黑市信誉很好。',
    attrs: { atk: 3, spd: 1, luck: -1 },
    freePoints: 3,
    startLingqi: 60,
    flags: ['birth_demon'],
    mark: '魔',
  },
  {
    id: 'herb_boy',
    name: '药园杂役',
    blurb: '识药辨草是吃饭的本事。丹师路过时，你总会多看一眼炉火。',
    attrs: { spirit: 3, luck: 1 },
    freePoints: 3,
    startLingqi: 30,
    flags: ['birth_herb'],
    mark: '药',
  },
  {
    id: 'hunter',
    name: '猎妖村落',
    blurb: '村里人人会下套。你童年玩具是妖兽牙齿。',
    attrs: { atk: 2, def: 1, spd: 2 },
    freePoints: 3,
    startLingqi: 20,
    flags: ['birth_hunter'],
    mark: '猎',
  },
  {
    id: 'trash_young',
    name: '废柴少爷',
    blurb: '三年之期已到？还没到。全城都在等你打脸剧情，你先摸鱼。',
    attrs: { luck: 3, bone: -1, spirit: 1 },
    freePoints: 5,
    startLingqi: 10,
    flags: ['birth_trash', 'trope_trash'],
    mark: '废',
  },
  {
    id: 'transmigrator',
    name: '莫名穿越者',
    blurb: '你记得斗气、遮天、仙逆的剧透，却记不住早饭吃了啥。系统？没有。',
    attrs: { spirit: 2, luck: 2, spd: 1 },
    freePoints: 4,
    startLingqi: 0,
    flags: ['birth_chuan', 'trope_meta'],
    mark: '穿',
  },
];

export const BRANCH_LABELS: Record<BranchId, { name: string; blurb: string; mult: number }> = {
  flame: { name: '焚炎异火', blurb: '斗破同款：火越大，面子越大。', mult: 1.12 },
  alchemy: { name: '丹道求索', blurb: '凡人同款：丹成，人未老。', mult: 1.1 },
  body: { name: '荒古体修', blurb: '遮天同款：肉身即道，拳可崩渊。', mult: 1.15 },
  soul: { name: '神魂仙逆', blurb: '仙逆同款：一念成魔，一念成佛。', mult: 1.14 },
  beast: { name: '驭兽灵契', blurb: '凡人同款：宠物才是战力本体。', mult: 1.11 },
  sword: { name: '问心一剑', blurb: '诸天同款：剑在人在，梗也在。', mult: 1.13 },
};

export const ARTS: ArtDef[] = [
  {
    id: 'tuna_basic',
    name: '基础吐纳',
    description: '每次吐纳吸入更多灵力。',
    kind: 'click',
    baseCost: 15,
    costMult: 1.13,
    power: 0.6,
    minRealm: 0,
    attrs: { bone: 0.1 },
    mark: '纳',
  },
  {
    id: 'meridian_open',
    name: '洗经伐脉',
    description: '疏通经脉，点击更猛。',
    kind: 'click',
    baseCost: 140,
    costMult: 1.15,
    power: 2.2,
    minRealm: 0,
    attrs: { bone: 0.2 },
    mark: '脉',
  },
  {
    id: 'qi_vortex',
    name: '气旋吞吐',
    description: '气海成涡，一吸千缕。',
    kind: 'click',
    baseCost: 1_200,
    costMult: 1.16,
    power: 9,
    minRealm: 1,
    attrs: { spirit: 0.2 },
    mark: '涡',
  },
  {
    id: 'dragon_breath',
    name: '龙息吐纳',
    description: '仿龙族呼吸，点击暴涨。',
    kind: 'click',
    baseCost: 1.5e4,
    costMult: 1.17,
    power: 38,
    minRealm: 3,
    attrs: { atk: 0.3 },
    mark: '龙',
  },
  {
    id: 'heaven_draw',
    name: '抽天夺气',
    description: '强抽天地灵气，凶险却快。',
    kind: 'click',
    baseCost: 2e5,
    costMult: 1.18,
    power: 150,
    minRealm: 5,
    attrs: { atk: 0.4, luck: -0.1 },
    mark: '夺',
  },
  {
    id: 'dao_inhale',
    name: '问道一吸',
    description: '大道呼吸，点击如潮。',
    kind: 'click',
    baseCost: 4e6,
    costMult: 1.2,
    power: 650,
    minRealm: 8,
    attrs: { spirit: 0.5 },
    mark: '道',
  },
  {
    id: 'sit_meditation',
    name: '静室打坐',
    description: '每秒缓慢积攒灵力。',
    kind: 'passive',
    baseCost: 50,
    costMult: 1.12,
    power: 0.4,
    minRealm: 0,
    attrs: { spirit: 0.1 },
    mark: '坐',
  },
  {
    id: 'spirit_gather',
    name: '聚灵阵纹',
    description: '洞府聚灵，被动提升。',
    kind: 'passive',
    baseCost: 400,
    costMult: 1.14,
    power: 2,
    minRealm: 1,
    mark: '阵',
  },
  {
    id: 'cave_mansion',
    name: '洞府灵脉',
    description: '占据灵脉，日夜滋养。',
    kind: 'passive',
    baseCost: 5_000,
    costMult: 1.15,
    power: 11,
    minRealm: 2,
    mark: '府',
  },
  {
    id: 'sect_salary',
    name: '宗门俸禄',
    description: '挂名领俸，月例化灵气。',
    kind: 'passive',
    baseCost: 4e4,
    costMult: 1.16,
    power: 48,
    minRealm: 3,
    mark: '俸',
  },
  {
    id: 'domain_tax',
    name: '领地气税',
    description: '以势压人，灵气上供。',
    kind: 'passive',
    baseCost: 3e5,
    costMult: 1.17,
    power: 190,
    minRealm: 5,
    mark: '税',
  },
  {
    id: 'void_well',
    name: '虚空灵井',
    description: '连通虚空，源源不断。',
    kind: 'passive',
    baseCost: 5e6,
    costMult: 1.18,
    power: 850,
    minRealm: 7,
    mark: '井',
  },
  {
    id: 'heaven_vein',
    name: '天脉共鸣',
    description: '与界域天脉共鸣。',
    kind: 'passive',
    baseCost: 8e7,
    costMult: 1.2,
    power: 3800,
    minRealm: 9,
    mark: '天',
  },
  // —— 体术通道 ——
  {
    id: 'fist_temper',
    name: '铁砂磨拳',
    description: '以拳锤体，点击增长体术。',
    kind: 'click',
    channel: 'tishu',
    baseCost: 18,
    costMult: 1.13,
    power: 0.55,
    minRealm: 0,
    attrs: { bone: 0.15 },
    mark: '拳',
  },
  {
    id: 'bone_forge',
    name: '锻骨千锤',
    description: '骨响如雷，点击体术暴涨。',
    kind: 'click',
    channel: 'tishu',
    baseCost: 1_600,
    costMult: 1.15,
    power: 8,
    minRealm: 1,
    attrs: { atk: 0.2, bone: 0.2 },
    mark: '锻',
  },
  {
    id: 'blood_surge',
    name: '气血潮生',
    description: '周身气血自行鼓荡。',
    kind: 'passive',
    channel: 'tishu',
    baseCost: 60,
    costMult: 1.12,
    power: 0.35,
    minRealm: 0,
    attrs: { def: 0.1 },
    mark: '血',
  },
  {
    id: 'marrow_wash',
    name: '洗髓易筋',
    description: '夜夜自淬，体术细水长流。',
    kind: 'passive',
    channel: 'tishu',
    baseCost: 4_500,
    costMult: 1.15,
    power: 10,
    minRealm: 2,
    attrs: { bone: 0.3 },
    mark: '髓',
  },
  // —— 精神力通道 ——
  {
    id: 'mind_focus',
    name: '凝神一念',
    description: '收束神识，点击增长精神力。',
    kind: 'click',
    channel: 'jingshen',
    baseCost: 18,
    costMult: 1.13,
    power: 0.55,
    minRealm: 0,
    attrs: { spirit: 0.15 },
    mark: '念',
  },
  {
    id: 'soul_sea',
    name: '识海开疆',
    description: '拓广识海，点击精神力暴涨。',
    kind: 'click',
    channel: 'jingshen',
    baseCost: 1_600,
    costMult: 1.15,
    power: 8,
    minRealm: 1,
    attrs: { spirit: 0.3 },
    mark: '海',
  },
  {
    id: 'spirit_hum',
    name: '神魂轻鸣',
    description: '神魂自转，精神力缓生。',
    kind: 'passive',
    channel: 'jingshen',
    baseCost: 60,
    costMult: 1.12,
    power: 0.35,
    minRealm: 0,
    attrs: { luck: 0.1 },
    mark: '鸣',
  },
  {
    id: 'void_gaze',
    name: '虚空观想',
    description: '观想虚空，精神力长流。',
    kind: 'passive',
    channel: 'jingshen',
    baseCost: 4_500,
    costMult: 1.15,
    power: 10,
    minRealm: 2,
    attrs: { spirit: 0.3 },
    mark: '观',
  },
  // 分支功法
  {
    id: 'flame_seed',
    name: '火种温养',
    description: '掌心火种助推吐纳。',
    kind: 'click',
    baseCost: 4_000,
    costMult: 1.16,
    power: 20,
    minRealm: 2,
    branch: 'flame',
    attrs: { atk: 0.4 },
    mark: '火',
  },
  {
    id: 'strange_fire',
    name: '异火残种',
    description: '异火淬体，被动灼烧杂质。',
    kind: 'passive',
    baseCost: 2.5e5,
    costMult: 1.17,
    power: 130,
    minRealm: 4,
    branch: 'flame',
    attrs: { atk: 0.6, bone: 0.3 },
    mark: '异',
  },
  {
    id: 'emperor_flame',
    name: '帝炎虚影',
    description: '帝级异火虚影，被动焚天。',
    kind: 'passive',
    baseCost: 9e7,
    costMult: 1.21,
    power: 4500,
    minRealm: 9,
    branch: 'flame',
    attrs: { atk: 1.2 },
    mark: '炎',
  },
  {
    id: 'herb_pick',
    name: '识药辨草',
    description: '采药入鼎，点击炼化。',
    kind: 'click',
    baseCost: 3_500,
    costMult: 1.15,
    power: 18,
    minRealm: 2,
    branch: 'alchemy',
    attrs: { spirit: 0.4 },
    mark: '药',
  },
  {
    id: 'soul_flame_refine',
    name: '魂火炼丹',
    description: '灵魂之火控丹。',
    kind: 'passive',
    baseCost: 2.4e5,
    costMult: 1.17,
    power: 135,
    minRealm: 4,
    branch: 'alchemy',
    attrs: { spirit: 0.7 },
    mark: '丹',
  },
  {
    id: 'pill_tower',
    name: '丹塔残卷',
    description: '丹道古籍加持。',
    kind: 'passive',
    baseCost: 8e7,
    costMult: 1.2,
    power: 4200,
    minRealm: 9,
    branch: 'alchemy',
    attrs: { spirit: 1.2, luck: 0.3 },
    mark: '塔',
  },
  {
    id: 'bone_temper',
    name: '锻骨淬筋',
    description: '以力破巧。',
    kind: 'click',
    baseCost: 3_800,
    costMult: 1.16,
    power: 22,
    minRealm: 2,
    branch: 'body',
    attrs: { bone: 0.5, def: 0.3 },
    mark: '骨',
  },
  {
    id: 'diamond_body',
    name: '霸体雏形',
    description: '肉身硬抗法术。',
    kind: 'passive',
    baseCost: 2.8e5,
    costMult: 1.17,
    power: 150,
    minRealm: 4,
    branch: 'body',
    attrs: { def: 0.8, bone: 0.5 },
    mark: '霸',
  },
  {
    id: 'immortal_flesh',
    name: '不灭肉身',
    description: '肉身近圣。',
    kind: 'passive',
    baseCost: 1e8,
    costMult: 1.21,
    power: 4800,
    minRealm: 9,
    branch: 'body',
    attrs: { def: 1.5, bone: 1 },
    mark: '灭',
  },
  {
    id: 'soul_sense',
    name: '神魂感知',
    description: '神识搜刮游离灵气。',
    kind: 'click',
    baseCost: 3_600,
    costMult: 1.16,
    power: 19,
    minRealm: 2,
    branch: 'soul',
    attrs: { spirit: 0.5 },
    mark: '识',
  },
  {
    id: 'soul_palace',
    name: '神魂殿台',
    description: '筑神魂殿。',
    kind: 'passive',
    baseCost: 2.6e5,
    costMult: 1.17,
    power: 140,
    minRealm: 4,
    branch: 'soul',
    attrs: { spirit: 0.9 },
    mark: '殿',
  },
  {
    id: 'heaven_soul',
    name: '逆仙残念',
    description: '沾染仙逆之意。',
    kind: 'passive',
    baseCost: 9e7,
    costMult: 1.21,
    power: 4600,
    minRealm: 9,
    branch: 'soul',
    attrs: { spirit: 1.4, atk: 0.4 },
    mark: '逆',
  },
  {
    id: 'beast_whisper',
    name: '兽语低语',
    description: '与灵兽沟通。',
    kind: 'click',
    baseCost: 3_400,
    costMult: 1.15,
    power: 17,
    minRealm: 2,
    branch: 'beast',
    attrs: { luck: 0.3, spd: 0.2 },
    mark: '语',
  },
  {
    id: 'winged_mount',
    name: '灵兽共修',
    description: '契约共享血脉。',
    kind: 'passive',
    baseCost: 2.5e5,
    costMult: 1.17,
    power: 128,
    minRealm: 4,
    branch: 'beast',
    attrs: { spd: 0.6, atk: 0.3 },
    mark: '契',
  },
  {
    id: 'beast_king_crown',
    name: '万兽朝拜',
    description: '兽潮听令。',
    kind: 'passive',
    baseCost: 8e7,
    costMult: 1.2,
    power: 4300,
    minRealm: 9,
    branch: 'beast',
    attrs: { atk: 0.8, luck: 0.6 },
    mark: '兽',
  },
  {
    id: 'sword_basic',
    name: '基础剑式',
    description: '以剑意引气。',
    kind: 'click',
    baseCost: 3_500,
    costMult: 1.16,
    power: 18,
    minRealm: 2,
    branch: 'sword',
    attrs: { atk: 0.4, spd: 0.2 },
    mark: '式',
  },
  {
    id: 'flying_sword',
    name: '御剑千里',
    description: '飞剑巡空搜灵。',
    kind: 'passive',
    baseCost: 2.5e5,
    costMult: 1.17,
    power: 132,
    minRealm: 4,
    branch: 'sword',
    attrs: { spd: 0.7, atk: 0.4 },
    mark: '御',
  },
  {
    id: 'heaven_slash',
    name: '开天一剑',
    description: '剑意问天。',
    kind: 'passive',
    baseCost: 9e7,
    costMult: 1.21,
    power: 4700,
    minRealm: 9,
    branch: 'sword',
    attrs: { atk: 1.3, spd: 0.5 },
    mark: '开',
  },
  {
    id: 'orthodox_edict',
    name: '正道敕令',
    description: '正道资源倾斜。',
    kind: 'passive',
    baseCost: 1e6,
    costMult: 1.16,
    power: 240,
    minRealm: 6,
    faction: 'orthodox',
    attrs: { def: 0.5, luck: 0.3 },
    mark: '正',
  },
  {
    id: 'dark_plunder',
    name: '魔功掠夺',
    description: '以掠夺换资源。',
    kind: 'click',
    baseCost: 9e5,
    costMult: 1.17,
    power: 280,
    minRealm: 6,
    faction: 'dark',
    attrs: { atk: 0.7 },
    mark: '魔',
  },
  {
    id: 'hermit_quiet',
    name: '隐世清修',
    description: '不问世事，效率奇高。',
    kind: 'passive',
    baseCost: 9e5,
    costMult: 1.16,
    power: 260,
    minRealm: 6,
    faction: 'hermit',
    attrs: { spirit: 0.6, luck: 0.4 },
    mark: '隐',
  },
];

export const ENEMIES: EnemyDef[] = [
  {
    id: 'rogue_qi',
    name: '黑衣劫修',
    blurb: '路口拦人：「把储物袋留下。」经典开局。',
    minRealm: 0,
    maxRealm: 2,
    attrs: { atk: 4, def: 3, spd: 4, spirit: 2, bone: 3, luck: 1 },
    rewardLingqi: 120,
    rewardPoints: 1,
    dropTreasureId: 'storage_pouch',
    dropChance: 0.25,
    lore: '凡人',
  },
  {
    id: 'clan_bully',
    name: '同族跋扈子弟',
    blurb: '「你也配练功？」——打脸进度条已加载。',
    minRealm: 0,
    maxRealm: 3,
    attrs: { atk: 6, def: 4, spd: 3, spirit: 3, bone: 4, luck: 2 },
    rewardLingqi: 280,
    rewardPoints: 1,
    dropTreasureId: 'face_slap_fan',
    dropChance: 0.2,
    lore: '斗破/诸天',
  },
  {
    id: 'demon_wolf',
    name: '血纹妖狼',
    blurb: '妖丹香喷喷，牙齿闪闪。',
    minRealm: 1,
    maxRealm: 4,
    attrs: { atk: 10, def: 7, spd: 12, spirit: 4, bone: 8, luck: 2 },
    rewardLingqi: 900,
    rewardPoints: 1,
    lore: '凡人',
  },
  {
    id: 'alchemy_thief',
    name: '夺丹贼',
    blurb: '专偷出炉金丹，职业素养拉满。',
    minRealm: 2,
    maxRealm: 5,
    attrs: { atk: 14, def: 8, spd: 16, spirit: 12, bone: 6, luck: 5 },
    rewardLingqi: 3_500,
    rewardPoints: 2,
    dropTreasureId: 'herb_pick' as unknown as string,
    dropChance: 0,
    lore: '凡人',
  },
  {
    id: 'fire_cultist',
    name: '炎蛇谷弟子',
    blurb: '浑身火属性，说话都带火星子。',
    minRealm: 2,
    maxRealm: 6,
    attrs: { atk: 18, def: 10, spd: 11, spirit: 9, bone: 10, luck: 4 },
    rewardLingqi: 6_000,
    rewardPoints: 2,
    dropTreasureId: 'flame_tome',
    dropChance: 0.15,
    lore: '斗破',
  },
  {
    id: 'holy_son',
    name: '某圣地圣子',
    blurb: '排面拉满，战力不一定。',
    minRealm: 4,
    maxRealm: 8,
    attrs: { atk: 35, def: 28, spd: 30, spirit: 32, bone: 30, luck: 20 },
    rewardLingqi: 8e4,
    rewardPoints: 3,
    dropTreasureId: 'desolate_bone',
    dropChance: 0.12,
    lore: '遮天',
  },
  {
    id: 'soul_old',
    name: '神魂老怪',
    blurb: '专夺舍，开口就是「好苗子」。',
    minRealm: 3,
    maxRealm: 7,
    attrs: { atk: 22, def: 15, spd: 18, spirit: 40, bone: 12, luck: 8 },
    rewardLingqi: 2.5e4,
    rewardPoints: 2,
    dropTreasureId: 'soul_lamp',
    dropChance: 0.18,
    lore: '仙逆/凡人',
  },
  {
    id: 'tribulation_echo',
    name: '心魔幻影',
    blurb: '长得像你，说话比你还毒。',
    minRealm: 7,
    maxRealm: 11,
    attrs: { atk: 80, def: 70, spd: 75, spirit: 90, bone: 70, luck: 40 },
    rewardLingqi: 5e6,
    rewardPoints: 4,
    dropTreasureId: 'plot_armor',
    dropChance: 0.1,
    lore: '诸天',
  },
  {
    id: 'heaven_envoy',
    name: '天道巡使',
    blurb: '来查你是否开挂。你心虚地摸了摸绿液小瓶。',
    minRealm: 8,
    maxRealm: 11,
    attrs: { atk: 120, def: 110, spd: 100, spirit: 130, bone: 100, luck: 60 },
    rewardLingqi: 3e7,
    rewardPoints: 5,
    dropTreasureId: 'heaven_stele',
    dropChance: 0.08,
    lore: '元梗',
  },
];

// Fix alchemy_thief bad drop - remove invalid drop
ENEMIES.forEach((e) => {
  if (e.id === 'alchemy_thief') {
    e.dropTreasureId = undefined;
    e.dropChance = undefined;
  }
});

export const STORY_EVENTS: StoryEventDef[] = [
  {
    id: 'choose_branch',
    title: '大道分岔',
    body: '结丹在即，诸天气机在眼前交织：异火、丹香、荒骨、神魂、兽语、剑意……选一条，走一世。',
    minRealm: 2,
    minStar: 3,
    lore: '融合',
    options: [
      { id: 'pick_flame', label: '焚炎', blurb: BRANCH_LABELS.flame.blurb, set: { branchId: 'flame' }, flags: ['path_flame'] },
      { id: 'pick_alchemy', label: '丹道', blurb: BRANCH_LABELS.alchemy.blurb, set: { branchId: 'alchemy' }, flags: ['path_alchemy'] },
      { id: 'pick_body', label: '体修', blurb: BRANCH_LABELS.body.blurb, set: { branchId: 'body' }, flags: ['path_body'] },
      { id: 'pick_soul', label: '神魂', blurb: BRANCH_LABELS.soul.blurb, set: { branchId: 'soul' }, flags: ['path_soul'] },
      { id: 'pick_beast', label: '驭兽', blurb: BRANCH_LABELS.beast.blurb, set: { branchId: 'beast' }, flags: ['path_beast'] },
      { id: 'pick_sword', label: '剑心', blurb: BRANCH_LABELS.sword.blurb, set: { branchId: 'sword' }, flags: ['path_sword'] },
    ],
  },
  {
    id: 'bottle_dream',
    title: '神秘小瓶',
    body: '梦里有人把一只不起眼的小瓶塞进你怀里：「养草用。」你醒来，枕头下真有一瓶绿液。',
    minRealm: 0,
    minStar: 2,
    lore: '凡人修仙',
    options: [
      {
        id: 'take_bottle',
        label: '收下（心虚）',
        blurb: '获得「绿液小瓶」。隔壁说你气运逆天。',
        flags: ['has_bottle'],
        grantTreasureId: 'small_bottle',
        qiyunDelta: 1,
      },
      {
        id: 'refuse_bottle',
        label: '怕是坑，埋了',
        blurb: '安全第一。错过主角标配，但心安。',
        flags: ['refused_bottle'],
        freePointsDelta: 1,
      },
    ],
  },
  {
    id: 'three_year_appoint',
    title: '三年之期',
    body: '有人当众立下赌约：三年后再战。全城都在围观，弹幕已经飘过「打脸预定」。',
    minRealm: 1,
    requireFlags: ['trope_trash'],
    lore: '斗破梗',
    options: [
      {
        id: 'accept_appoint',
        label: '接下赌约',
        blurb: '获得「打脸扇」线索与属性激励。',
        flags: ['three_year'],
        freePointsDelta: 2,
        attrsDelta: { atk: 2, luck: 1 },
        grantTreasureId: 'face_slap_fan',
      },
      {
        id: 'ignore_appoint',
        label: '当听不见',
        blurb: '低调发育，拒绝剧本。',
        flags: ['skip_appoint'],
        lingqiDelta: 500,
      },
    ],
  },
  {
    id: 'flame_trial',
    title: '火山试炼',
    body: '地底异火残息扑面。斗破粉丝的手在抖：这是要发了？',
    minRealm: 3,
    requireBranch: 'flame',
    lore: '斗破苍穹',
    options: [
      {
        id: 'flame_swallow',
        label: '强行吞纳',
        blurb: '险中求胜，获异火亲和与火种。',
        flags: ['strange_fire_affinity'],
        grantTreasureId: 'fire_lotus',
        lingqiDelta: -2e4,
        qiyunDelta: 1,
        attrsDelta: { atk: 3, bone: 1 },
        combatEnemyId: 'fire_cultist',
        deathOnLose: true,
        deathReason: '异火反噬，形神俱灭',
      },
      {
        id: 'flame_nurture',
        label: '稳妥温养',
        blurb: '根基更稳。',
        flags: ['fire_lotus_seed'],
        lingqiDelta: 1e4,
        attrsDelta: { bone: 2 },
      },
    ],
  },
  {
    id: 'alchemy_auction',
    title: '坊市丹拍',
    body: '黑市出现残缺丹方。凡人式选择：砸灵石，还是动歪脑筋？',
    minRealm: 3,
    requireBranch: 'alchemy',
    lore: '凡人修仙',
    options: [
      {
        id: 'alchemy_bid',
        label: '倾囊竞拍',
        blurb: '换得丹缘，丹塔日后或认你。',
        flags: ['pill_formula', 'dantower_favor'],
        lingqiDelta: -5e4,
        attrsDelta: { spirit: 2 },
      },
      {
        id: 'alchemy_steal',
        label: '神识偷记',
        blurb: '记下半卷，染上盗方之名。',
        flags: ['pill_formula', 'thief_name'],
        lingqiDelta: -5e3,
        attrsDelta: { spirit: 1, luck: -1 },
      },
    ],
  },
  {
    id: 'body_arena',
    title: '角斗场',
    body: '有人以重金请你硬碰。遮天体修表示：正好热身。',
    minRealm: 3,
    requireBranch: 'body',
    lore: '遮天',
    options: [
      {
        id: 'body_fight',
        label: '下场硬碰',
        blurb: '打出名号，也可能被抬出去。',
        flags: ['undying_title'],
        combatEnemyId: 'demon_wolf',
        deathOnLose: false,
        freePointsDelta: 1,
        attrsDelta: { bone: 2, def: 2 },
        grantTreasureId: 'desolate_bone',
      },
      {
        id: 'body_refuse',
        label: '拒而不战',
        blurb: '潜心锻体。',
        flags: ['quiet_temper'],
        lingqiDelta: 2e4,
      },
    ],
  },
  {
    id: 'soul_whisper',
    title: '骨骸低语',
    body: '荒野骨堆有残魂求你带走：「带我，教你逆天之术。」仙逆警告灯闪烁。',
    minRealm: 3,
    requireBranch: 'soul',
    lore: '仙逆',
    options: [
      {
        id: 'soul_accept',
        label: '收纳残魂',
        blurb: '得魂灯，亦沾怨毒。',
        flags: ['heaven_soul_clue', 'resentment'],
        grantTreasureId: 'soul_lamp',
        qiyunDelta: 1,
        attrsDelta: { spirit: 3 },
      },
      {
        id: 'soul_seal',
        label: '镇压超度',
        blurb: '心境清明。',
        flags: ['pure_soul'],
        lingqiDelta: 1.5e4,
        attrsDelta: { luck: 2 },
      },
    ],
  },
  {
    id: 'beast_egg',
    title: '古兽蛋',
    body: '山谷里一枚兽蛋在发光。养它还是卖它？这是个问题。',
    minRealm: 3,
    requireBranch: 'beast',
    lore: '凡人',
    options: [
      {
        id: 'beast_hatch',
        label: '以血孵化',
        blurb: '结生死契。',
        flags: ['ancient_companion'],
        lingqiDelta: -1.5e4,
        qiyunDelta: 1,
        attrsDelta: { luck: 2, spd: 2 },
      },
      {
        id: 'beast_sell',
        label: '卖予商会',
        blurb: '财富自由一小步。',
        flags: ['sold_destiny'],
        lingqiDelta: 8e4,
      },
    ],
  },
  {
    id: 'sword_grave',
    title: '剑冢一夜',
    body: '万剑嗡鸣，古剑悬于眉心。你脑内自动响起 BGM。',
    minRealm: 3,
    requireBranch: 'sword',
    lore: '诸天剑修',
    options: [
      {
        id: 'sword_bond',
        label: '以心认剑',
        blurb: '剑意入体。',
        flags: ['heart_sword'],
        grantTreasureId: 'bamboo_cloud_sword',
        lingqiDelta: -1e4,
        attrsDelta: { atk: 2, spd: 2 },
      },
      {
        id: 'sword_leave',
        label: '一拜离去',
        blurb: '不贪不执。',
        flags: ['sword_empty'],
        lingqiDelta: 2e4,
        freePointsDelta: 1,
      },
    ],
  },
  {
    id: 'possession_crisis',
    title: '夺舍危机',
    body: '一位「和蔼前辈」盯着你的身体：「 generational talent啊。」你起了一身鸡皮疙瘩。',
    minRealm: 4,
    lore: '凡人/仙逆',
    options: [
      {
        id: 'pos_fight',
        label: '神魂对轰',
        blurb: '拼神识！输了可能直接去世。',
        combatEnemyId: 'soul_old',
        deathOnLose: true,
        deathReason: '被老怪夺舍，此世落幕',
        flags: ['resisted_possession'],
        attrsDelta: { spirit: 3 },
        freePointsDelta: 1,
      },
      {
        id: 'pos_fake',
        label: '装死装傻',
        blurb: '用剧情护甲糊弄过去（或许）。',
        flags: ['played_dead'],
        grantTreasureId: 'plot_armor',
        lingqiDelta: -5e3,
      },
      {
        id: 'pos_sell',
        label: '主动交易残魂',
        blurb: '危险交易，换山河车残轮。',
        flags: ['deal_with_old'],
        grantTreasureId: 'mountain_river',
        attrsDelta: { luck: -2, spirit: 2 },
      },
    ],
  },
  {
    id: 'choose_faction',
    title: '阵营招揽',
    body: '大乘在望，三方使者同日至府：正道盟、魔宗余党、隐世散修。群消息已读不回会被踢。',
    minRealm: 6,
    minStar: 1,
    lore: '融合',
    options: [
      {
        id: 'fac_orthodox',
        label: '加入正道',
        blurb: '资源与枷锁。',
        set: { factionId: 'orthodox' },
        flags: ['faction_orthodox'],
        lingqiDelta: 5e5,
        attrsDelta: { def: 2, luck: 1 },
      },
      {
        id: 'fac_dark',
        label: '投向魔道',
        blurb: '自由与血腥。',
        set: { factionId: 'dark' },
        flags: ['faction_dark'],
        lingqiDelta: 8e5,
        qiyunDelta: -1,
        attrsDelta: { atk: 3 },
      },
      {
        id: 'fac_hermit',
        label: '隐世散修',
        blurb: '无人搅扰，亦无人援手。',
        set: { factionId: 'hermit' },
        flags: ['faction_hermit'],
        qiyunDelta: 2,
        attrsDelta: { spirit: 2, luck: 2 },
      },
    ],
  },
  {
    id: 'dark_massacre',
    title: '血夜任务',
    body: '魔宗命你屠城拒贡者。任务栏闪红：道德值警告。',
    minRealm: 7,
    requireFaction: 'dark',
    lore: '魔道',
    options: [
      {
        id: 'dark_kill',
        label: '血洗全城',
        blurb: '魔名远扬。',
        flags: ['demon_lord_seed', 'blood_hands'],
        lingqiDelta: 2e6,
        attrsDelta: { atk: 4, luck: -2 },
      },
      {
        id: 'dark_fake',
        label: '假报军情',
        blurb: '暗中放人。',
        flags: ['double_face'],
        lingqiDelta: -4e5,
        qiyunDelta: 1,
      },
    ],
  },
  {
    id: 'orthodox_trial',
    title: '正道大比',
    body: '联盟大比，邀你压阵。镜头已经对准你的脸。',
    minRealm: 7,
    requireFaction: 'orthodox',
    lore: '正道',
    options: [
      {
        id: 'ortho_win',
        label: '全力夺魁',
        blurb: '盟主之位相露。先打一场。',
        flags: ['alliance_leader'],
        combatEnemyId: 'holy_son',
        deathOnLose: false,
        lingqiDelta: 1e6,
        qiyunDelta: 1,
        freePointsDelta: 2,
      },
      {
        id: 'ortho_hide',
        label: '点到为止',
        blurb: '少树敌。',
        flags: ['steady_name'],
        lingqiDelta: 4e5,
      },
    ],
  },
  {
    id: 'choose_destiny',
    title: '气运抉择',
    body: '渡劫前夕，天道降下三道气机：证道、守界、问虚空。',
    minRealm: 8,
    minStar: 4,
    lore: '融合',
    options: [
      {
        id: 'des_emperor',
        label: '执意证道',
        blurb: '赌那一线大道。',
        set: { destinyId: 'emperor' },
        flags: ['destiny_emperor'],
        qiyunDelta: -2,
        attrsDelta: { atk: 3, spirit: 3 },
      },
      {
        id: 'des_guardian',
        label: '镇守界域',
        blurb: '护一方生灵。',
        set: { destinyId: 'guardian' },
        flags: ['destiny_guardian'],
        qiyunDelta: 3,
        attrsDelta: { def: 3, luck: 2 },
      },
      {
        id: 'des_void',
        label: '问道虚空',
        blurb: '抛下界域，追逐未知。',
        set: { destinyId: 'void' },
        flags: ['destiny_void'],
        lingqiDelta: 5e7,
        attrsDelta: { spd: 3, spirit: 2 },
      },
    ],
  },
  {
    id: 'heaven_tribulation',
    title: '天劫将至',
    body: '九色雷云压顶。渡劫选项已刷新——请勿使用外挂。',
    minRealm: 8,
    minStar: 7,
    lore: '凡人/诸天',
    options: [
      {
        id: 'trib_hard',
        label: '肉身硬抗',
        blurb: '输了就死。',
        flags: ['survived_tribulation'],
        combatEnemyId: 'tribulation_echo',
        deathOnLose: true,
        deathReason: '天劫劈成焦炭，此世轮回',
        lingqiDelta: -1e8,
        qiyunDelta: 2,
        attrsDelta: { bone: 5, def: 3 },
      },
      {
        id: 'trib_array',
        label: '借聚灵阵',
        blurb: '稳妥渡劫。',
        flags: ['array_tribulation'],
        lingqiDelta: -3e7,
        attrsDelta: { spirit: 2 },
      },
      {
        id: 'trib_sacrifice',
        label: '移花接木',
        blurb: '灾移他人，欠因果。',
        flags: ['karmic_debt', 'blood_hands'],
        lingqiDelta: 5e7,
        qiyunDelta: -3,
      },
    ],
  },
  {
    id: 'meta_system',
    title: '疑似系统弹窗',
    body: '眼前闪过一行字：「签到领奖？」你作为穿越者激动了 0.5 秒，发现是骗子阵法。',
    minRealm: 1,
    requireFlags: ['trope_meta'],
    lore: '元梗',
    options: [
      {
        id: 'meta_punch',
        label: '一拳砸烂',
        blurb: '清醒。获自由属性点。',
        flags: ['no_system'],
        freePointsDelta: 2,
        combatEnemyId: 'rogue_qi',
      },
      {
        id: 'meta_click',
        label: '手贱点一下',
        blurb: '被吸走灵气，但悟到一点「剧情护甲」之法。',
        flags: ['almost_scammed'],
        lingqiDelta: -200,
        grantTreasureId: 'plot_armor',
      },
    ],
  },
  {
    id: 'final_gate',
    title: '大道之门',
    body: '金仙巅峰，一道门虚影现于云端。跨入与否，决定此世收束。',
    minRealm: 10,
    minStar: 8,
    lore: '大道',
    options: [
      {
        id: 'gate_enter',
        label: '踏入道门',
        blurb: '赌那成道一线。或触发对战。',
        flags: ['entered_dao_gate'],
        grantTreasureId: 'dao_seed',
        combatEnemyId: 'heaven_envoy',
        deathOnLose: true,
        deathReason: '道门反噬，形神俱灭',
        lingqiDelta: -5e10,
      },
      {
        id: 'gate_wait',
        label: '暂且观望',
        blurb: '再积气运。',
        flags: ['patient_wait'],
        qiyunDelta: 2,
        freePointsDelta: 2,
      },
    ],
  },
  {
    id: 'roadside_robbery',
    title: '经典拦路',
    body: '「此山是我开……」你听过一千遍。要打吗？',
    minRealm: 0,
    minStar: 4,
    lore: '凡人',
    options: [
      {
        id: 'rob_fight',
        label: '拼了',
        blurb: '对战黑衣劫修。败了丢脸丢灵气，暂不致死。',
        combatEnemyId: 'rogue_qi',
        deathOnLose: false,
        freePointsDelta: 1,
        lingqiDelta: -20,
      },
      {
        id: 'rob_pay',
        label: '破财免灾',
        blurb: '给灵气走人。',
        lingqiDelta: -80,
        flags: ['paid_road'],
      },
      {
        id: 'rob_run',
        label: '拔腿就跑',
        blurb: '身法检定……算你跑掉。',
        attrsDelta: { spd: 1 },
        flags: ['ran_away'],
      },
    ],
  },
];

/** 可重复随机奇遇：点击 / 升层 / 定时触发 */
export const RANDOM_EVENTS: StoryEventDef[] = [
  {
    id: 'rnd_herb',
    title: '路边灵草',
    body: '一株发着微光的草在石缝里晃。采？还是怀疑是诱饵？',
    minRealm: 0,
    lore: '凡人',
    repeatable: true,
    weight: 2,
    options: [
      {
        id: 'herb_pick',
        label: '采了',
        blurb: '灵气小涨，根骨微微发烫。',
        lingqiDelta: 80,
        attrsDelta: { bone: 1 },
      },
      {
        id: 'herb_pass',
        label: '可疑，路过',
        blurb: '安全第一。气机 +1。',
        attrsDelta: { luck: 1 },
      },
    ],
  },
  {
    id: 'rnd_auction_rumor',
    title: '坊市传闻',
    body: '有人低声说：今晚黑市有「打脸扇」仿品。你耳朵动了动。',
    minRealm: 1,
    lore: '诸天梗',
    repeatable: true,
    weight: 1,
    options: [
      {
        id: 'rumor_go',
        label: '去瞧瞧',
        blurb: '花点灵气，说不定有收获。',
        lingqiDelta: -200,
        freePointsDelta: 1,
      },
      {
        id: 'rumor_ignore',
        label: '传闻而已',
        blurb: '继续吐纳。',
        lingqiDelta: 40,
      },
    ],
  },
  {
    id: 'rnd_duel_invite',
    title: '切磋战帖',
    body: '一名同境修士扔来战帖：「比划比划？」围观群众已就位。',
    minRealm: 0,
    lore: '斗破/凡人',
    repeatable: true,
    weight: 2,
    options: [
      {
        id: 'duel_yes',
        label: '接战',
        blurb: '拼属性！败不致死。',
        combatEnemyId: 'clan_bully',
        deathOnLose: false,
        freePointsDelta: 1,
      },
      {
        id: 'duel_no',
        label: '闭关谢客',
        blurb: '低调发育。',
        attrsDelta: { spirit: 1 },
      },
    ],
  },
  {
    id: 'rnd_cave',
    title: '无名洞府',
    body: '山壁裂开一道缝，里面隐约有储物袋的味道。',
    minRealm: 1,
    lore: '凡人',
    repeatable: true,
    weight: 1,
    options: [
      {
        id: 'cave_enter',
        label: '探进去',
        blurb: '可能遇劫修，也可能发财。',
        combatEnemyId: 'rogue_qi',
        deathOnLose: false,
        lingqiDelta: 300,
        grantTreasureId: 'storage_pouch',
      },
      {
        id: 'cave_leave',
        label: '洞里有坑',
        blurb: '你选择相信直觉。',
        attrsDelta: { luck: 1 },
      },
    ],
  },
  {
    id: 'rnd_dream',
    title: '梦中残响',
    body: '梦里有人喊「三年之期已到」，你吓醒了。窗外其实才三天。',
    minRealm: 0,
    lore: '斗破梗',
    repeatable: true,
    weight: 1,
    options: [
      {
        id: 'dream_train',
        label: '倒是刺激，加练',
        blurb: '攻伐微增。',
        attrsDelta: { atk: 1 },
        lingqiDelta: -30,
      },
      {
        id: 'dream_sleep',
        label: '翻个身继续睡',
        blurb: '神识回笼。',
        attrsDelta: { spirit: 1 },
      },
    ],
  },
  {
    id: 'rnd_wolf',
    title: '林中妖嚎',
    body: '血纹妖狼的气息靠近。打还是绕？',
    minRealm: 1,
    lore: '凡人',
    repeatable: true,
    weight: 1,
    options: [
      {
        id: 'wolf_fight',
        label: '猎之',
        blurb: '对战妖狼。',
        combatEnemyId: 'demon_wolf',
        deathOnLose: false,
        freePointsDelta: 1,
      },
      {
        id: 'wolf_sneak',
        label: '屏息绕行',
        blurb: '身法经验 +1。',
        attrsDelta: { spd: 1 },
      },
    ],
  },
  {
    id: 'rnd_merchant',
    title: '游方商人',
    body: '「小友，看一看，瞧一瞧，保真的荒古……仿制品。」',
    minRealm: 2,
    lore: '遮天梗',
    repeatable: true,
    weight: 1,
    options: [
      {
        id: 'merch_buy',
        label: '买个心理安慰',
        blurb: '破财，气机微妙上升。',
        lingqiDelta: -1500,
        attrsDelta: { luck: 2 },
      },
      {
        id: 'merch_haggle',
        label: '神识扫货',
        blurb: '识破假货，商人灰溜溜离开。你赚了点面子和灵气。',
        lingqiDelta: 200,
        attrsDelta: { spirit: 1 },
      },
    ],
  },
  {
    id: 'rnd_soul_wind',
    title: '阴风一阵',
    body: '神魂波动扫过识海。像有人在找「好苗子」。',
    minRealm: 3,
    lore: '仙逆',
    repeatable: true,
    weight: 1,
    options: [
      {
        id: 'soul_resist',
        label: '稳住神魂',
        blurb: '神识对抗成功。',
        attrsDelta: { spirit: 2 },
        combatEnemyId: 'soul_old',
        deathOnLose: false,
      },
      {
        id: 'soul_hide',
        label: '龟息藏匿',
        blurb: '暂避锋芒。',
        attrsDelta: { def: 1, luck: 1 },
      },
    ],
  },
  {
    id: 'rnd_pill_smell',
    title: '丹香扑鼻',
    body: '山谷里飘来丹香。是机缘，还是「请君入瓮」？凡人读者表示很熟。',
    minRealm: 1,
    lore: '凡人',
    repeatable: true,
    weight: 2,
    options: [
      {
        id: 'pill_enter',
        label: '循香而入',
        blurb: '灵气大涨，也可能被丹毒呛到。',
        lingqiDelta: 600,
        attrsDelta: { bone: 1, luck: -1 },
      },
      {
        id: 'pill_watch',
        label: '远远观望',
        blurb: '记下方位，神识+1。',
        attrsDelta: { spirit: 1 },
      },
    ],
  },
  {
    id: 'rnd_ancient_tomb',
    title: '无名古墓',
    body: '墓砖上写着「生人勿近」。你附近的穿越者已经开始搜刮了。',
    minRealm: 2,
    lore: '遮天梗',
    repeatable: true,
    weight: 1,
    options: [
      {
        id: 'tomb_dig',
        label: '挖！',
        blurb: '有利有弊：灵气与属性乱跳。',
        lingqiDelta: 2_000,
        attrsDelta: { atk: 1, def: -1, luck: 1 },
        freePointsDelta: 1,
      },
      {
        id: 'tomb_bow',
        label: '一拜离去',
        blurb: '心境清明。',
        attrsDelta: { spirit: 2, luck: 1 },
      },
    ],
  },
  {
    id: 'rnd_fake_master',
    title: '收徒骗子',
    body: '一位「隐世高人」要收你为徒，先交三千灵石拜师费。',
    minRealm: 0,
    lore: '诸天梗',
    repeatable: true,
    weight: 2,
    options: [
      {
        id: 'fake_pay',
        label: '交了',
        blurb: '被坑。但「吃一堑」换气机？没有，就是被坑。',
        lingqiDelta: -300,
        attrsDelta: { luck: -1 },
      },
      {
        id: 'fake_expose',
        label: '当场拆穿',
        blurb: '骗子逃跑，围观群众鼓掌。自由点+1。',
        freePointsDelta: 1,
        attrsDelta: { spirit: 1 },
      },
    ],
  },
  {
    id: 'rnd_dual_cult',
    title: '可疑双修邀约',
    body: '有人传音：「双修可速成。」你的系统……哦你没有系统，只有常识。',
    minRealm: 2,
    lore: '诸天梗',
    repeatable: true,
    weight: 1,
    options: [
      {
        id: 'dual_no',
        label: '拒绝（保命）',
        blurb: '正确选项。神识+1。',
        attrsDelta: { spirit: 1, luck: 1 },
      },
      {
        id: 'dual_trap',
        label: '赴约看看',
        blurb: '果然是陷阱。掉点灵气，长点记性。',
        lingqiDelta: -800,
        attrsDelta: { def: 1 },
        combatEnemyId: 'alchemy_thief',
        deathOnLose: false,
      },
    ],
  },
];

export const ENDINGS: EndingDef[] = [
  {
    id: 'yan_di',
    name: '炎帝余烬',
    title: '异火归位，焚尽诸天阻拦',
    body: '你以焚炎走通大道，火种与帝炎虚影共鸣。有人说你像极了某本小说的封面。',
    priority: 100,
    minRealm: 11,
    requireBranch: 'flame',
    requireFlags: ['strange_fire_affinity', 'entered_dao_gate'],
    requireArts: { emperor_flame: 1 },
    requireTreasures: ['fire_lotus'],
  },
  {
    id: 'pill_sovereign',
    name: '药尊真人',
    title: '丹香覆陆，药成而道成',
    body: '丹道残卷在你掌中续写。凡人式结局：活得够久，才看得够远。',
    priority: 95,
    minRealm: 11,
    requireBranch: 'alchemy',
    requireFlags: ['dantower_favor', 'pill_formula'],
    requireArts: { pill_tower: 1 },
  },
  {
    id: 'undying_body',
    name: '荒古不灭',
    title: '肉身成道，拳碎天劫',
    body: '遮天式收束：你不靠外物，筋骨血气撞开道门。',
    priority: 95,
    minRealm: 11,
    requireBranch: 'body',
    requireFlags: ['undying_title', 'survived_tribulation'],
    requireArts: { immortal_flesh: 1 },
    requireTreasures: ['desolate_bone'],
  },
  {
    id: 'soul_heaven',
    name: '逆仙一念',
    title: '神魂覆天，一念成道',
    body: '仙逆之意在你眉心睁眼。世人称你为逆。',
    priority: 95,
    minRealm: 11,
    requireBranch: 'soul',
    requireFlags: ['heaven_soul_clue', 'entered_dao_gate'],
    requireArts: { heaven_soul: 1 },
    requireTreasures: ['soul_lamp'],
  },
  {
    id: 'beast_sovereign',
    name: '万兽共主',
    title: '兽潮听令，共主临世',
    body: '契约铺满星空，你更像兽原之王。',
    priority: 95,
    minRealm: 11,
    requireBranch: 'beast',
    requireFlags: ['ancient_companion'],
    requireArts: { beast_king_crown: 1 },
  },
  {
    id: 'sword_heaven',
    name: '剑开天门',
    title: '一剑问道，门开而落',
    body: '心剑出鞘，天门为你而裂。',
    priority: 95,
    minRealm: 11,
    requireBranch: 'sword',
    requireFlags: ['heart_sword', 'entered_dao_gate'],
    requireArts: { heaven_slash: 1 },
  },
  {
    id: 'bottle_immortal',
    name: '瓶中仙',
    title: '绿液养尽仙途',
    body: '你从未解释过那只小瓶。但草木、丹药与气运，都站在你这边。',
    priority: 92,
    minRealm: 10,
    requireFlags: ['has_bottle'],
    requireTreasures: ['small_bottle'],
    minQiyun: 5,
  },
  {
    id: 'demon_lord',
    name: '魔君临世',
    title: '血夜之后，魔名覆城',
    body: '你以魔功踏入大道，界域战栗。',
    priority: 90,
    minRealm: 11,
    requireFaction: 'dark',
    requireFlags: ['demon_lord_seed', 'blood_hands'],
  },
  {
    id: 'alliance_king',
    name: '正道盟主',
    title: '敕令天下，盟主镇世',
    body: '正道大旗在你身后展开。',
    priority: 88,
    minRealm: 11,
    requireFaction: 'orthodox',
    requireFlags: ['alliance_leader'],
    requireDestiny: 'guardian',
  },
  {
    id: 'void_wanderer',
    name: '虚空行者',
    title: '弃界问虚，行踪无定',
    body: '你未坐道座，却走进更深虚空。',
    priority: 88,
    minRealm: 10,
    requireDestiny: 'void',
  },
  {
    id: 'hermit_immortal',
    name: '逍遥散仙',
    title: '隐世清修，道成无声',
    body: '无人知你姓名，只在无名峰顶有帝光一闪。',
    priority: 85,
    minRealm: 11,
    requireFaction: 'hermit',
    requireDestiny: 'guardian',
  },
  {
    id: 'karmic_fall',
    name: '因果陨落',
    title: '债满身灭，道门崩塌',
    body: '移花接木的天劫回来了。你在门前散作飞灰。',
    priority: 120,
    minRealm: 9,
    requireFlags: ['karmic_debt', 'entered_dao_gate'],
  },
  {
    id: 'face_slap_god',
    name: '打脸成圣',
    title: '三年之期，全城沉默',
    body: '你兑现了所有赌约。打脸扇成为文物。',
    priority: 86,
    minRealm: 8,
    requireFlags: ['three_year', 'trope_trash'],
    requireTreasures: ['face_slap_fan'],
    minAttrs: { atk: 40 },
  },
  {
    id: 'patient_emperor',
    name: '隐忍成道',
    title: '观望千日，一朝登临',
    body: '你未急着踏门，气运堆满，终以最稳姿态成道。',
    priority: 80,
    minRealm: 11,
    requireFlags: ['patient_wait'],
    requireDestiny: 'emperor',
    minQiyun: 8,
  },
  {
    id: 'default_dao',
    name: '道成诸天',
    title: '大道落座，诸天侧目',
    body: '无论道途如何，你终站上巅峰。此世落幕，轮回可再启，法宝与属性或可继承。',
    priority: 10,
    minRealm: 11,
  },
  {
    id: 'fallen_wild',
    name: '荒野枯骨',
    title: '气散人亡，无名冢',
    body: '此世太短。有人在荒野见过一具枯骨，储物袋是空的。',
    priority: 5,
    minRealm: 0,
  },
];

export function getRealm(index: number): RealmDef {
  return REALMS[Math.max(0, Math.min(REALMS.length - 1, index))]!;
}

export function getArt(id: string): ArtDef | undefined {
  return ARTS.find((a) => a.id === id);
}

export function getBirth(id: string): BirthDef | undefined {
  return BIRTHS.find((b) => b.id === id);
}

export function getTreasure(id: string): TreasureDef | undefined {
  return TREASURES.find((t) => t.id === id);
}

export function getEnemy(id: string): EnemyDef | undefined {
  return ENEMIES.find((e) => e.id === id);
}

export function getEnding(id: string): EndingDef | undefined {
  return ENDINGS.find((e) => e.id === id);
}
