import type { EquipSlot, EquippedMap, NaturalDef, StoryEventDef, TreasureDef } from './types';
import { EQUIP_SLOTS } from './types';

/**
 * 各槽容量随境界扩充：
 * 战斗：0→1，3→2，7→3
 * 修炼：0→1，2→2，6→3
 * 辅助：0→1，4→2，8→3
 */
export function slotCapacity(realmIndex: number): Record<EquipSlot, number> {
  return {
    combat: 1 + (realmIndex >= 3 ? 1 : 0) + (realmIndex >= 7 ? 1 : 0),
    cultivate: 1 + (realmIndex >= 2 ? 1 : 0) + (realmIndex >= 6 ? 1 : 0),
    assist: 1 + (realmIndex >= 4 ? 1 : 0) + (realmIndex >= 8 ? 1 : 0),
  };
}

export function emptyEquipped(realmIndex = 0): EquippedMap {
  const cap = slotCapacity(realmIndex);
  const eq = {} as EquippedMap;
  for (const slot of EQUIP_SLOTS) {
    eq[slot] = Array.from({ length: cap[slot] }, () => null);
  }
  return eq;
}

/** 展平已装备法宝 id（去空） */
export function listEquippedIds(equipped: EquippedMap): string[] {
  const ids: string[] = [];
  for (const slot of EQUIP_SLOTS) {
    for (const id of equipped[slot] || []) {
      if (id) ids.push(id);
    }
  }
  return ids;
}

/**
 * 法宝：正向越多负面越重；仙品无负面。
 * 炼器耗体术放大正面；洗练耗体术抹除负面（仙品无需）。
 */
export const TREASURES: TreasureDef[] = [
  // —— 战斗 · 凡品 ——
  {
    id: 'bamboo_cloud_sword',
    name: '青竹蜂云剑残锋',
    description: '战斗槽。凡人同款飞剑残锋，御剑时总想喊出剑名。',
    lore: '凡人修仙',
    cost: 2_500,
    minRealm: 1,
    tier: 'mortal',
    pros: ['攻伐+4', '身法+2', '战力×1.08', '先手'],
    cons: {
      attrs: { def: -2, bone: -1 },
      labels: ['护体-2', '根骨-1', '剑意伤己'],
    },
    slot: 'combat',
    attrs: { atk: 4, spd: 2 },
    combatMult: 1.08,
    combatEdges: { firstStrikeChance: 0.18, firstStrikeBonus: 0.12 },
    maxTemper: 5,
    temperBaseCost: 80,
    refineCost: 400,
    sellLingli: 1_200,
    mark: '竹',
    vaultable: true,
  },
  {
    id: 'face_slap_fan',
    name: '打脸扇',
    description: '战斗槽。专治各种不服。',
    lore: '诸天梗',
    cost: 3_000,
    minRealm: 1,
    tier: 'mortal',
    pros: ['攻伐+3', '气机+2', '暴击/先手'],
    cons: {
      attrs: { spirit: -2 },
      combatMult: 0.97,
      labels: ['神识-2', '战力×0.97', '招人记恨'],
    },
    slot: 'combat',
    attrs: { atk: 3, luck: 2 },
    combatMult: 1.07,
    combatEdges: { critChance: 0.2, critMult: 1.35, firstStrikeChance: 0.12, firstStrikeBonus: 0.08 },
    maxTemper: 5,
    temperBaseCost: 90,
    refineCost: 450,
    sellLingli: 1_400,
    mark: '扇',
    vaultable: true,
  },
  {
    id: 'rusty_spear',
    name: '锈蚀猎妖矛',
    description: '战斗槽。外门弟子入门标配，扎得准但沉。',
    lore: '凡人',
    cost: 600,
    minRealm: 0,
    tier: 'mortal',
    pros: ['攻伐+2', '战力×1.04'],
    cons: {
      attrs: { spd: -1 },
      labels: ['身法-1'],
    },
    slot: 'combat',
    attrs: { atk: 2 },
    combatMult: 1.04,
    maxTemper: 4,
    temperBaseCost: 40,
    refineCost: 200,
    sellLingli: 280,
    mark: '矛',
    vaultable: false,
  },
  {
    id: 'blood_dagger',
    name: '饮血短匕',
    description: '战斗槽。见血则快，亦易反噬。',
    lore: '魔道',
    cost: 4_500,
    minRealm: 1,
    tier: 'mortal',
    pros: ['攻伐+5', '身法+3', '暴击', '战力×1.09'],
    cons: {
      attrs: { def: -3, luck: -2 },
      triadBias: { jingshen: -0.03 },
      labels: ['护体-3', '气机-2', '抑精神产出'],
    },
    slot: 'combat',
    attrs: { atk: 5, spd: 3 },
    combatMult: 1.09,
    combatEdges: { critChance: 0.18, critMult: 1.4 },
    maxTemper: 5,
    temperBaseCost: 100,
    refineCost: 520,
    sellLingli: 2_000,
    mark: '匕',
    vaultable: true,
  },
  {
    id: 'thunder_ring',
    name: '裂空雷环',
    description: '战斗槽。一掷惊雷，耳鸣三日。',
    lore: '斗破',
    cost: 1.2e4,
    minRealm: 2,
    tier: 'mortal',
    pros: ['攻伐+6', '神识+2', '先手', '战力×1.1'],
    cons: {
      attrs: { bone: -2, spirit: -1 },
      cultivatePassive: -1,
      labels: ['根骨-2', '神识-1', '被动修炼-1'],
    },
    slot: 'combat',
    attrs: { atk: 6, spirit: 2 },
    combatMult: 1.1,
    combatEdges: { firstStrikeChance: 0.22, firstStrikeBonus: 0.14 },
    maxTemper: 6,
    temperBaseCost: 160,
    refineCost: 800,
    sellLingli: 5_500,
    mark: '雷',
    vaultable: true,
  },
  // —— 战斗 · 灵品 ——
  {
    id: 'flame_tome',
    name: '焚诀残页',
    description: '战斗槽。斗破同款：练着练着就想找异火。',
    lore: '斗破苍穹',
    cost: 6_000,
    minRealm: 2,
    tier: 'spirit',
    pros: ['攻伐+6', '根骨+1', '暴击', '战力×1.1'],
    cons: {
      attrs: { luck: -2, def: -1 },
      triadBias: { tishu: -0.02, lingli: 0.02 },
      labels: ['气机-2', '护体-1', '偏灵抑体'],
    },
    slot: 'combat',
    attrs: { atk: 6, bone: 1 },
    combatMult: 1.1,
    combatEdges: { critChance: 0.16, critMult: 1.45 },
    maxTemper: 7,
    temperBaseCost: 200,
    refineCost: 1_200,
    sellLingli: 2_800,
    mark: '焚',
    vaultable: true,
  },
  {
    id: 'fire_lotus',
    name: '青莲地心火种',
    description: '战斗槽。小小火种，战意沸腾。',
    lore: '斗破苍穹',
    cost: 0,
    minRealm: 3,
    tier: 'spirit',
    pros: ['攻伐+8', '神识+2', '高暴击', '战力×1.14'],
    cons: {
      attrs: { bone: -3, def: -2 },
      combatMult: 0.96,
      triadBias: { jingshen: -0.04 },
      labels: ['根骨-3', '护体-2', '战力×0.96', '抑精神'],
    },
    slot: 'combat',
    attrs: { atk: 8, spirit: 2 },
    combatMult: 1.14,
    combatEdges: { critChance: 0.22, critMult: 1.55 },
    maxTemper: 8,
    temperBaseCost: 280,
    refineCost: 2_000,
    sellLingli: 8_000,
    mark: '莲',
    vaultable: true,
  },
  {
    id: 'heaven_slash_blade',
    name: '开天残刃',
    description: '战斗槽。剑意未散，杀气犹存。',
    lore: '诸天剑修',
    cost: 8e4,
    minRealm: 5,
    tier: 'spirit',
    pros: ['攻伐+12', '身法+4', '暴击/先手', '战力×1.16'],
    cons: {
      attrs: { luck: -4, spirit: -2, def: -3 },
      cultivateClick: -2,
      labels: ['气机-4', '神识-2', '护体-3', '点击修炼-2'],
    },
    slot: 'combat',
    attrs: { atk: 12, spd: 4 },
    combatMult: 1.16,
    combatEdges: { critChance: 0.25, critMult: 1.65, firstStrikeChance: 0.2, firstStrikeBonus: 0.15 },
    maxTemper: 8,
    temperBaseCost: 600,
    refineCost: 5_000,
    sellLingli: 3.5e4,
    mark: '刃',
    vaultable: true,
  },
  {
    id: 'shadow_bow',
    name: '追影神弓',
    description: '战斗槽。一箭追魂，却易漏防。',
    lore: '诸天',
    cost: 2.5e4,
    minRealm: 3,
    tier: 'spirit',
    pros: ['攻伐+7', '身法+5', '先手/闪避', '战力×1.12'],
    cons: {
      attrs: { def: -4, bone: -2 },
      triadBias: { lingli: -0.03 },
      labels: ['护体-4', '根骨-2', '抑灵力产出'],
    },
    slot: 'combat',
    attrs: { atk: 7, spd: 5 },
    combatMult: 1.12,
    combatEdges: { firstStrikeChance: 0.2, firstStrikeBonus: 0.12, dodgeChance: 0.12 },
    maxTemper: 7,
    temperBaseCost: 320,
    refineCost: 2_400,
    sellLingli: 1.1e4,
    mark: '弓',
    vaultable: true,
  },
  {
    id: 'demon_blade',
    name: '魔煞刀胚',
    description: '战斗槽。刀鸣如哭，越杀越强。',
    lore: '仙逆',
    cost: 4.5e4,
    minRealm: 4,
    tier: 'spirit',
    pros: ['攻伐+10', '气机+3', '暴击', '战力×1.15', '战力特效'],
    cons: {
      attrs: { spirit: -5, luck: -3, def: -2 },
      combatMult: 0.94,
      triadBias: { jingshen: -0.05, tishu: 0.02 },
      labels: ['神识-5', '气机-3', '护体-2', '战力×0.94', '抑神助体'],
    },
    slot: 'combat',
    attrs: { atk: 10, luck: 3 },
    combatMult: 1.15,
    combatEdges: { critChance: 0.28, critMult: 1.7 },
    maxTemper: 8,
    temperBaseCost: 450,
    refineCost: 3_600,
    sellLingli: 2e4,
    mark: '煞',
    vaultable: true,
  },
  // —— 战斗 · 仙品 ——
  {
    id: 'immortal_sword_intent',
    name: '一缕剑意',
    description: '战斗槽。仙品。无瑕剑意，无负面。',
    lore: '大道',
    cost: 0,
    minRealm: 8,
    tier: 'immortal',
    pros: ['攻伐+18', '身法+8', '神识+4', '极高暴击/先手', '战力×1.22'],
    slot: 'combat',
    attrs: { atk: 18, spd: 8, spirit: 4 },
    combatMult: 1.22,
    combatEdges: {
      critChance: 0.3,
      critMult: 1.8,
      firstStrikeChance: 0.25,
      firstStrikeBonus: 0.2,
    },
    maxTemper: 9,
    temperBaseCost: 2_000,
    refineCost: 0,
    sellLingli: 2e5,
    mark: '意',
    vaultable: true,
  },
  // —— 修炼 · 凡品 ——
  {
    id: 'small_bottle',
    name: '绿液小瓶',
    description: '修炼槽。滴草木疯长；略微调和三才。',
    lore: '凡人修仙',
    cost: 0,
    minRealm: 0,
    tier: 'mortal',
    pros: ['气机+3', '根骨+2', '神识+1', '点击+2', '被动+1.5', '调和'],
    cons: {
      attrs: { atk: -2 },
      triadBias: { tishu: -0.02 },
      labels: ['攻伐-2', '抑体术产出', '药瘾'],
    },
    slot: 'cultivate',
    attrs: { luck: 3, bone: 2, spirit: 1 },
    cultivateClick: 2,
    cultivatePassive: 1.5,
    triadDamp: 0.12,
    maxTemper: 6,
    temperBaseCost: 60,
    refineCost: 350,
    sellLingli: 800,
    mark: '瓶',
    vaultable: true,
  },
  {
    id: 'spirit_gather_jade',
    name: '聚灵玉简',
    description: '修炼槽。玉简贴身聚灵；偏助灵力。',
    lore: '凡人修仙',
    cost: 1_800,
    minRealm: 0,
    tier: 'mortal',
    pros: ['神识+2', '点击+1', '被动+2.5', '调和', '偏灵'],
    cons: {
      attrs: { bone: -1 },
      triadBias: { tishu: -0.03 },
      labels: ['根骨-1', '抑体更甚'],
    },
    slot: 'cultivate',
    attrs: { spirit: 2 },
    cultivateClick: 1,
    cultivatePassive: 2.5,
    triadDamp: 0.08,
    triadBias: { lingli: 0.04, tishu: -0.02 },
    maxTemper: 5,
    temperBaseCost: 50,
    refineCost: 280,
    sellLingli: 900,
    mark: '玉',
    vaultable: true,
  },
  {
    id: 'meditation_mat',
    name: '破蒲团',
    description: '修炼槽。坐久了腿麻，但心静。',
    lore: '诸天',
    cost: 350,
    minRealm: 0,
    tier: 'mortal',
    pros: ['神识+1', '被动+1'],
    cons: {
      attrs: { spd: -1 },
      labels: ['身法-1'],
    },
    slot: 'cultivate',
    attrs: { spirit: 1 },
    cultivatePassive: 1,
    maxTemper: 4,
    temperBaseCost: 30,
    refineCost: 150,
    sellLingli: 160,
    mark: '团',
    vaultable: false,
  },
  {
    id: 'qi_pill_furnace',
    name: '聚气小炉',
    description: '修炼槽。炉火旺则灵气涌，亦耗神。',
    lore: '凡人',
    cost: 5_500,
    minRealm: 1,
    tier: 'mortal',
    pros: ['点击+3', '被动+3', '神识+2'],
    cons: {
      attrs: { luck: -2 },
      triadBias: { jingshen: -0.04 },
      labels: ['气机-2', '抑精神产出'],
    },
    slot: 'cultivate',
    attrs: { spirit: 2 },
    cultivateClick: 3,
    cultivatePassive: 3,
    maxTemper: 5,
    temperBaseCost: 110,
    refineCost: 600,
    sellLingli: 2_400,
    mark: '炉',
    vaultable: true,
  },
  // —— 修炼 · 灵品 ——
  {
    id: 'desolate_bone',
    name: '荒古残骨',
    description: '修炼槽。根骨发光；偏助体术。',
    lore: '遮天',
    cost: 1.2e4,
    minRealm: 2,
    tier: 'spirit',
    pros: ['根骨+5', '护体+2', '点击+3', '被动+4', '调和', '偏体'],
    cons: {
      attrs: { spirit: -3, luck: -1 },
      cultivateClick: -1,
      labels: ['神识-3', '气机-1', '点击-1', '骨寒侵神'],
    },
    slot: 'cultivate',
    attrs: { bone: 5, def: 2 },
    cultivateClick: 3,
    cultivatePassive: 4,
    triadDamp: 0.1,
    triadBias: { tishu: 0.06, jingshen: -0.02 },
    maxTemper: 7,
    temperBaseCost: 220,
    refineCost: 1_500,
    sellLingli: 5_500,
    mark: '荒',
    vaultable: true,
  },
  {
    id: 'mountain_river',
    name: '山河车残轮',
    description: '修炼槽。山河轮转，三才互扰显著减弱。',
    lore: '仙逆',
    cost: 2e4,
    minRealm: 3,
    tier: 'spirit',
    pros: ['神识+4', '点击+2', '被动+6', '强调和'],
    cons: {
      attrs: { atk: -3, spd: -2 },
      triadBias: { lingli: -0.02 },
      labels: ['攻伐-3', '身法-2', '抑灵力'],
    },
    slot: 'cultivate',
    attrs: { spirit: 4 },
    cultivateClick: 2,
    cultivatePassive: 6,
    triadDamp: 0.28,
    maxTemper: 7,
    temperBaseCost: 300,
    refineCost: 2_200,
    sellLingli: 9_000,
    mark: '车',
    vaultable: true,
  },
  {
    id: 'nine_turn_manual',
    name: '九转残诀',
    description: '修炼槽。转得越快越饿，也越容易走火。',
    lore: '遮天',
    cost: 3.5e4,
    minRealm: 4,
    tier: 'spirit',
    pros: ['根骨+4', '神识+3', '点击+5', '被动+8', '调和'],
    cons: {
      attrs: { luck: -4, def: -2 },
      combatMult: 0.95,
      triadBias: { jingshen: -0.03, tishu: -0.02 },
      labels: ['气机-4', '护体-2', '战力×0.95', '双抑'],
    },
    slot: 'cultivate',
    attrs: { bone: 4, spirit: 3 },
    cultivateClick: 5,
    cultivatePassive: 8,
    triadDamp: 0.15,
    maxTemper: 8,
    temperBaseCost: 400,
    refineCost: 3_000,
    sellLingli: 1.5e4,
    mark: '转',
    vaultable: true,
  },
  {
    id: 'void_lotus_seat',
    name: '虚空莲台',
    description: '修炼槽。坐上空灵，站起脚软。',
    lore: '遮天',
    cost: 6e4,
    minRealm: 5,
    tier: 'spirit',
    pros: ['神识+6', '气机+3', '被动+10', '强调和', '偏神'],
    cons: {
      attrs: { bone: -4, atk: -2 },
      cultivateClick: -2,
      labels: ['根骨-4', '攻伐-2', '点击-2'],
    },
    slot: 'cultivate',
    attrs: { spirit: 6, luck: 3 },
    cultivatePassive: 10,
    triadDamp: 0.22,
    triadBias: { jingshen: 0.05, tishu: -0.03 },
    maxTemper: 8,
    temperBaseCost: 520,
    refineCost: 4_000,
    sellLingli: 2.6e4,
    mark: '台',
    vaultable: true,
  },
  // —— 修炼 · 仙品 ——
  {
    id: 'dao_seed',
    name: '道种一枚',
    description: '修炼槽。仙品。大道将成，近乎抹平三才偏科。',
    lore: '大道',
    cost: 0,
    minRealm: 10,
    tier: 'immortal',
    pros: ['神识+8', '根骨+8', '气机+5', '点击+20', '被动+40', '极调和'],
    slot: 'cultivate',
    attrs: { spirit: 8, bone: 8, luck: 5 },
    cultivateClick: 20,
    cultivatePassive: 40,
    triadDamp: 0.55,
    triadBias: { lingli: 0.03, tishu: 0.03, jingshen: 0.03 },
    maxTemper: 9,
    temperBaseCost: 3_000,
    refineCost: 0,
    sellLingli: 5e5,
    mark: '种',
    vaultable: true,
  },
  {
    id: 'immortal_breath_bead',
    name: '仙息珠',
    description: '修炼槽。仙品。一吸一呼，三才自衡。',
    lore: '仙逆',
    cost: 2e6,
    minRealm: 7,
    tier: 'immortal',
    pros: ['全属性+', '点击+12', '被动+25', '极调和'],
    slot: 'cultivate',
    attrs: { atk: 3, def: 3, spd: 3, spirit: 6, bone: 6, luck: 4 },
    cultivateClick: 12,
    cultivatePassive: 25,
    triadDamp: 0.5,
    maxTemper: 9,
    temperBaseCost: 2_500,
    refineCost: 0,
    sellLingli: 4e5,
    mark: '息',
    vaultable: true,
  },
  // —— 辅助 · 凡品 ——
  {
    id: 'storage_pouch',
    name: '下品储物袋',
    description: '辅助槽。能装灵草；微弱调和。',
    lore: '诸天通用',
    cost: 400,
    minRealm: 0,
    tier: 'mortal',
    pros: ['气机+2', '微调和'],
    cons: {
      attrs: { atk: -1 },
      labels: ['攻伐-1'],
    },
    slot: 'assist',
    attrs: { luck: 2 },
    triadDamp: 0.05,
    maxTemper: 3,
    temperBaseCost: 25,
    refineCost: 120,
    sellLingli: 180,
    mark: '袋',
    vaultable: false,
  },
  {
    id: 'spirit_boat',
    name: '破旧灵舟',
    description: '辅助槽。逃命一流；偏身法。',
    lore: '凡人修仙',
    cost: 8_000,
    minRealm: 2,
    tier: 'mortal',
    pros: ['身法+6', '护体+1', '闪避', '偏体'],
    cons: {
      attrs: { spirit: -2 },
      triadBias: { lingli: -0.03 },
      labels: ['神识-2', '抑灵力'],
    },
    slot: 'assist',
    attrs: { spd: 6, def: 1 },
    combatEdges: { dodgeChance: 0.22 },
    triadBias: { tishu: 0.04, lingli: -0.02 },
    maxTemper: 5,
    temperBaseCost: 140,
    refineCost: 700,
    sellLingli: 3_600,
    mark: '舟',
    vaultable: true,
  },
  {
    id: 'lucky_coin',
    name: '半真半假气运钱',
    description: '辅助槽。有时真有用，有时纯心理安慰。',
    lore: '诸天梗',
    cost: 2_200,
    minRealm: 0,
    tier: 'mortal',
    pros: ['气机+4', '闪避微弱'],
    cons: {
      attrs: { bone: -2 },
      labels: ['根骨-2', '赌徒气质'],
    },
    slot: 'assist',
    attrs: { luck: 4 },
    combatEdges: { dodgeChance: 0.06 },
    maxTemper: 4,
    temperBaseCost: 70,
    refineCost: 360,
    sellLingli: 1_000,
    mark: '钱',
    vaultable: true,
  },
  {
    id: 'ward_talisman',
    name: '护身符箓',
    description: '辅助槽。挡一刀的份。',
    lore: '凡人',
    cost: 1_500,
    minRealm: 0,
    tier: 'mortal',
    pros: ['护体+3', '免死微弱'],
    cons: {
      attrs: { spd: -1 },
      labels: ['身法-1'],
    },
    slot: 'assist',
    attrs: { def: 3 },
    combatEdges: { plotArmorChance: 0.08 },
    maxTemper: 4,
    temperBaseCost: 55,
    refineCost: 300,
    sellLingli: 700,
    mark: '符',
    vaultable: false,
  },
  // —— 辅助 · 灵品 ——
  {
    id: 'soul_lamp',
    name: '魂灯一盏',
    description: '辅助槽。照见心魔；偏神识。',
    lore: '仙逆',
    cost: 0,
    minRealm: 4,
    tier: 'spirit',
    pros: ['神识+6', '气机+2', '战力×1.03', '闪避/免死', '调和', '偏神'],
    cons: {
      attrs: { bone: -3, atk: -2 },
      triadBias: { tishu: -0.04 },
      labels: ['根骨-3', '攻伐-2', '抑体更甚', '灯影噬神'],
    },
    slot: 'assist',
    attrs: { spirit: 6, luck: 2 },
    combatMult: 1.03,
    combatEdges: { dodgeChance: 0.1, plotArmorChance: 0.12 },
    triadDamp: 0.1,
    triadBias: { jingshen: 0.05, tishu: -0.03 },
    maxTemper: 7,
    temperBaseCost: 260,
    refineCost: 1_800,
    sellLingli: 1.2e4,
    mark: '灯',
    vaultable: true,
  },
  {
    id: 'plot_armor',
    name: '剧情护甲',
    description: '辅助槽。作者亲女儿限定；强力抹平三才偏科。',
    lore: '元梗',
    cost: 0,
    minRealm: 0,
    tier: 'spirit',
    pros: ['护体+5', '气机+6', '战力×1.06', '强免死', '极调和'],
    cons: {
      attrs: { atk: -4, spirit: -2 },
      cultivatePassive: -2,
      labels: ['攻伐-4', '神识-2', '被动-2', '主角光环反噬'],
    },
    slot: 'assist',
    attrs: { def: 5, luck: 6 },
    combatMult: 1.06,
    combatEdges: { plotArmorChance: 0.35, dodgeChance: 0.08 },
    triadDamp: 0.35,
    maxTemper: 6,
    temperBaseCost: 180,
    refineCost: 2_500,
    sellLingli: 1e4,
    mark: '甲',
    vaultable: true,
  },
  {
    id: 'cauldron_lid',
    name: '青铜鼎盖',
    description: '辅助槽。盖上能砸人；丹道调和。',
    lore: '遮天',
    cost: 4e4,
    minRealm: 4,
    tier: 'spirit',
    pros: ['护体+6', '神识+3', '气机+1', '免死', '调和', '偏神灵'],
    cons: {
      attrs: { spd: -4 },
      combatMult: 0.97,
      labels: ['身法-4', '战力×0.97', '笨重'],
    },
    slot: 'assist',
    attrs: { def: 6, spirit: 3, luck: 1 },
    combatEdges: { plotArmorChance: 0.15 },
    triadDamp: 0.15,
    triadBias: { jingshen: 0.03, lingli: 0.03, tishu: -0.02 },
    maxTemper: 7,
    temperBaseCost: 380,
    refineCost: 2_800,
    sellLingli: 1.8e4,
    mark: '鼎',
    vaultable: true,
  },
  {
    id: 'heaven_stele',
    name: '残破天碑',
    description: '辅助槽。碑上有「道」；强力调和三才。',
    lore: '遮天/诸天',
    cost: 5e5,
    minRealm: 6,
    tier: 'spirit',
    pros: ['神识+8', '根骨+3', '气机+3', '战力×1.05', '先手/免死', '极调和'],
    cons: {
      attrs: { atk: -3, spd: -3, luck: -2 },
      cultivateClick: -3,
      triadBias: { tishu: -0.03 },
      labels: ['攻伐-3', '身法-3', '气机-2', '点击-3', '抑体'],
    },
    slot: 'assist',
    attrs: { spirit: 8, bone: 3, luck: 3 },
    combatMult: 1.05,
    combatEdges: { firstStrikeChance: 0.15, firstStrikeBonus: 0.1, plotArmorChance: 0.1 },
    triadDamp: 0.4,
    maxTemper: 8,
    temperBaseCost: 800,
    refineCost: 6_000,
    sellLingli: 1.8e5,
    mark: '碑',
    vaultable: true,
  },
  {
    id: 'mirror_of_heart',
    name: '照心古镜',
    description: '辅助槽。照破幻象，也照见自己的丑。',
    lore: '仙逆',
    cost: 2.8e4,
    minRealm: 3,
    tier: 'spirit',
    pros: ['神识+5', '气机+2', '闪避', '调和'],
    cons: {
      attrs: { luck: -3 },
      triadBias: { lingli: -0.02 },
      labels: ['气机-3', '抑灵', '心魔反视'],
    },
    slot: 'assist',
    attrs: { spirit: 5, luck: 2 },
    combatEdges: { dodgeChance: 0.15 },
    triadDamp: 0.18,
    maxTemper: 6,
    temperBaseCost: 240,
    refineCost: 1_600,
    sellLingli: 1.2e4,
    mark: '镜',
    vaultable: true,
  },
  {
    id: 'beast_taming_flute',
    name: '驭兽骨笛',
    description: '辅助槽。唤兽护体，笛声扰神。',
    lore: '凡人',
    cost: 1.5e4,
    minRealm: 2,
    tier: 'spirit',
    pros: ['护体+4', '根骨+2', '免死', '偏体'],
    cons: {
      attrs: { spirit: -3 },
      cultivatePassive: -1.5,
      labels: ['神识-3', '被动-1.5'],
    },
    slot: 'assist',
    attrs: { def: 4, bone: 2 },
    combatEdges: { plotArmorChance: 0.14 },
    triadBias: { tishu: 0.04, jingshen: -0.02 },
    maxTemper: 6,
    temperBaseCost: 200,
    refineCost: 1_300,
    sellLingli: 6_500,
    mark: '笛',
    vaultable: true,
  },
  // —— 辅助 · 仙品 ——
  {
    id: 'immortal_jade_seal',
    name: '仙玉印',
    description: '辅助槽。仙品。印落则安，无瑕无垢。',
    lore: '大道',
    cost: 0,
    minRealm: 9,
    tier: 'immortal',
    pros: ['护体+10', '神识+6', '气机+6', '战力×1.1', '强免死/闪避', '极调和'],
    slot: 'assist',
    attrs: { def: 10, spirit: 6, luck: 6 },
    combatMult: 1.1,
    combatEdges: { plotArmorChance: 0.4, dodgeChance: 0.2 },
    triadDamp: 0.45,
    maxTemper: 9,
    temperBaseCost: 2_200,
    refineCost: 0,
    sellLingli: 3e5,
    mark: '印',
    vaultable: true,
  },
];

/** 天才地宝：不占槽，直接加灵气 + 本世永久被动 */
export const NATURALS: NaturalDef[] = [
  {
    id: 'nat_spirit_grass',
    name: '百年灵草',
    description: '入口清凉，灵气立涨。',
    lore: '凡人',
    minRealm: 0,
    lingqiGain: 400,
    passiveBonus: 0.3,
    mark: '草',
    weight: 3,
  },
  {
    id: 'nat_beast_core',
    name: '一阶妖丹',
    description: '腥香扑鼻，炼化后底盘更厚。',
    lore: '凡人',
    minRealm: 1,
    lingqiGain: 1_200,
    passiveBonus: 0.8,
    mark: '丹',
    weight: 2,
  },
  {
    id: 'nat_fire_crystal',
    name: '地心火晶',
    description: '烫手，但吞下去修炼如坐火山口。',
    lore: '斗破',
    minRealm: 2,
    lingqiGain: 4_000,
    passiveBonus: 1.5,
    mark: '晶',
    weight: 2,
  },
  {
    id: 'nat_void_flower',
    name: '虚空莲瓣',
    description: '摘一片，寿元似有所感。',
    lore: '遮天',
    minRealm: 3,
    lingqiGain: 1.2e4,
    passiveBonus: 3,
    mark: '莲',
    weight: 1,
  },
  {
    id: 'nat_soul_dew',
    name: '神魂甘露',
    description: '一滴入识海，杂念退散。',
    lore: '仙逆',
    minRealm: 3,
    lingqiGain: 1e4,
    passiveBonus: 2.5,
    mark: '露',
    weight: 1,
  },
  {
    id: 'nat_dragon_blood',
    name: '龙血残渣',
    description: '腥烈，根骨隐隐发烫。',
    lore: '诸天',
    minRealm: 4,
    lingqiGain: 5e4,
    passiveBonus: 5,
    mark: '龙',
    weight: 1,
  },
  {
    id: 'nat_heaven_marrow',
    name: '天髓一缕',
    description: '罕见至极，灵力如潮。',
    lore: '遮天',
    minRealm: 6,
    lingqiGain: 5e5,
    passiveBonus: 12,
    mark: '髓',
    weight: 1,
  },
  {
    id: 'nat_dao_fruit',
    name: '半颗道果',
    description: '咬一口，像被天道瞪了一眼。',
    lore: '大道',
    minRealm: 8,
    lingqiGain: 8e6,
    passiveBonus: 30,
    mark: '果',
    weight: 1,
  },
];

/**
 * 主线剧情：由随机事件池触发，按 mainChapter 顺序推进。
 * 机缘为主，不全是战斗。
 */
export const MAIN_STORY: StoryEventDef[] = [
  {
    id: 'main_1_sect',
    title: '【主线】外门记名',
    body: '宗门外门招人。你可以用灵石买个记名，也可以去猎妖证明自己。凡人开局经典二选一。',
    minRealm: 0,
    lore: '凡人修仙·主线',
    mainChapter: 1,
    repeatable: false,
    options: [
      {
        id: 'm1_buy',
        label: '砸灵石记名',
        blurb: '花灵气入门，得储物袋与一点面子。',
        lingqiDelta: -150,
        grantTreasureId: 'storage_pouch',
        freePointsDelta: 1,
        flags: ['main_sect'],
      },
      {
        id: 'm1_hunt',
        label: '猎妖证明',
        blurb: '打一场；胜则入门，败不致死。',
        combatEnemyId: 'demon_wolf',
        deathOnLose: false,
        grantTreasureId: 'spirit_gather_jade',
        flags: ['main_sect'],
        freePointsDelta: 1,
      },
    ],
  },
  {
    id: 'main_2_market',
    title: '【主线】坊市风云',
    body: '坊市出现一份残卷拍卖。有人说是焚诀，有人说是骗局。你的气运在骰子上跳舞。',
    minRealm: 1,
    lore: '斗破/凡人·主线',
    mainChapter: 2,
    options: [
      {
        id: 'm2_bid',
        label: '咬牙竞拍',
        blurb: '可能拍到焚诀残页，也可能被割韭菜。',
        lingqiDelta: -3_000,
        grantTreasureId: 'flame_tome',
        flags: ['main_market'],
        attrsDelta: { luck: -1, atk: 1 },
      },
      {
        id: 'm2_steal_look',
        label: '神识偷瞄',
        blurb: '记下三行口诀，染上「小偷」闲话。',
        flags: ['main_market', 'thief_name'],
        attrsDelta: { spirit: 2, luck: -1 },
        lingqiDelta: 200,
      },
      {
        id: 'm2_leave',
        label: '冷静离场',
        blurb: '不赌。得百年灵草机缘。',
        flags: ['main_market'],
        freePointsDelta: 1,
        lingqiDelta: 800,
        grantNaturalId: 'nat_spirit_grass',
      },
    ],
  },
  {
    id: 'main_3_secret',
    title: '【主线】秘境开启',
    body: '界域秘境裂缝张开。里面有天才地宝的气味，也有老怪的呼吸。',
    minRealm: 2,
    lore: '诸天·主线',
    mainChapter: 3,
    options: [
      {
        id: 'm3_deep',
        label: '直闯深处',
        blurb: '高风险：遇老怪；高收益：虚空莲瓣。',
        combatEnemyId: 'soul_old',
        deathOnLose: false,
        flags: ['main_secret'],
        attrsDelta: { atk: 2 },
        grantNaturalId: 'nat_void_flower',
      },
      {
        id: 'm3_edge',
        label: '外围捡漏',
        blurb: '稳妥得妖丹与灵气。',
        flags: ['main_secret'],
        lingqiDelta: 5_000,
        freePointsDelta: 1,
        grantNaturalId: 'nat_beast_core',
      },
      {
        id: 'm3_map',
        label: '卖地图赚钱',
        blurb: '凡人式选择：不装英雄，先搞钱。',
        flags: ['main_secret', 'sold_map'],
        lingqiDelta: 1.5e4,
        attrsDelta: { luck: 1 },
      },
    ],
  },
  {
    id: 'main_4_tribulation_rumor',
    title: '【主线】天劫预言',
    body: '有人立牌：「三年后此间有劫。」你想起斗破的三年之期，笑了笑，又笑不出来。',
    minRealm: 4,
    lore: '斗破梗·主线',
    mainChapter: 4,
    options: [
      {
        id: 'm4_prepare',
        label: '闭关备劫',
        blurb: '属性稳增，得剧情护甲（心理安慰）。',
        flags: ['main_trib_ready'],
        grantTreasureId: 'plot_armor',
        attrsDelta: { def: 3, bone: 2 },
        freePointsDelta: 2,
      },
      {
        id: 'm4_ignore',
        label: '预言不可信',
        blurb: '继续浪。气机+2，但无准备。',
        flags: ['main_trib_ignore'],
        attrsDelta: { luck: 2 },
        lingqiDelta: 2e4,
      },
    ],
  },
  {
    id: 'main_5_dao_ask',
    title: '【主线】问道残碑',
    body: '天碑半截立于云上。碑文模糊，却像在问：你为何修仙？',
    minRealm: 6,
    lore: '遮天/大道·主线',
    mainChapter: 5,
    options: [
      {
        id: 'm5_power',
        label: '为了变强',
        blurb: '攻伐道心。得残破天碑。',
        flags: ['main_dao_power'],
        grantTreasureId: 'heaven_stele',
        attrsDelta: { atk: 4, spirit: 2 },
      },
      {
        id: 'm5_live',
        label: '为了活着',
        blurb: '凡人真心。护体与气机上升。',
        flags: ['main_dao_live'],
        attrsDelta: { def: 4, luck: 3 },
        freePointsDelta: 2,
      },
      {
        id: 'm5_void',
        label: '为了看见更高处',
        blurb: '问虚之念。神识大涨。',
        flags: ['main_dao_void'],
        attrsDelta: { spirit: 5, spd: 2 },
        lingqiDelta: 1e5,
      },
    ],
  },
];

export function getNatural(id: string): NaturalDef | undefined {
  return NATURALS.find((n) => n.id === id);
}
