import type { EquippedMap, NaturalDef, StoryEventDef, TreasureDef } from './types';

export function emptyEquipped(): EquippedMap {
  return { combat: null, cultivate: null, assist: null };
}

/** 法宝：分战斗 / 修炼 / 辅助三槽，互不干扰 */
export const TREASURES: TreasureDef[] = [
  // —— 战斗 ——
  {
    id: 'bamboo_cloud_sword',
    name: '青竹蜂云剑残锋',
    description: '战斗槽。凡人同款飞剑残锋，御剑时总想喊出剑名。',
    lore: '凡人修仙',
    cost: 2_500,
    minRealm: 1,
    slot: 'combat',
    attrs: { atk: 4, spd: 2 },
    combatMult: 1.08,
    mark: '竹',
    vaultable: true,
  },
  {
    id: 'flame_tome',
    name: '焚诀残页',
    description: '战斗槽。斗破同款：练着练着就想找异火。',
    lore: '斗破苍穹',
    cost: 6_000,
    minRealm: 2,
    slot: 'combat',
    attrs: { atk: 6, bone: 1 },
    combatMult: 1.1,
    mark: '焚',
    vaultable: true,
  },
  {
    id: 'fire_lotus',
    name: '青莲地心火种',
    description: '战斗槽。小小火种，战意沸腾。',
    lore: '斗破苍穹',
    cost: 0,
    minRealm: 3,
    slot: 'combat',
    attrs: { atk: 8, spirit: 2 },
    combatMult: 1.14,
    mark: '莲',
    vaultable: true,
  },
  {
    id: 'face_slap_fan',
    name: '打脸扇',
    description: '战斗槽。专治各种不服。',
    lore: '诸天梗',
    cost: 3_000,
    minRealm: 1,
    slot: 'combat',
    attrs: { atk: 3, luck: 2 },
    combatMult: 1.07,
    mark: '扇',
    vaultable: true,
  },
  {
    id: 'heaven_slash_blade',
    name: '开天残刃',
    description: '战斗槽。剑意未散，杀气犹存。',
    lore: '诸天剑修',
    cost: 8e4,
    minRealm: 5,
    slot: 'combat',
    attrs: { atk: 12, spd: 4 },
    combatMult: 1.16,
    mark: '刃',
    vaultable: true,
  },
  // —— 修炼 ——
  {
    id: 'small_bottle',
    name: '绿液小瓶',
    description: '修炼槽。滴草木疯长，吐纳也跟着开挂。',
    lore: '凡人修仙',
    cost: 0,
    minRealm: 0,
    slot: 'cultivate',
    attrs: { luck: 3, bone: 2, spirit: 1 },
    cultivateClick: 2,
    cultivatePassive: 1.5,
    mark: '瓶',
    vaultable: true,
  },
  {
    id: 'spirit_gather_jade',
    name: '聚灵玉简',
    description: '修炼槽。玉简贴身，被动聚灵。',
    lore: '凡人修仙',
    cost: 1_800,
    minRealm: 0,
    slot: 'cultivate',
    attrs: { spirit: 2 },
    cultivateClick: 1,
    cultivatePassive: 2.5,
    mark: '玉',
    vaultable: true,
  },
  {
    id: 'desolate_bone',
    name: '荒古残骨',
    description: '修炼槽。摸一下根骨都在发光，打坐事半功倍。',
    lore: '遮天',
    cost: 1.2e4,
    minRealm: 2,
    slot: 'cultivate',
    attrs: { bone: 5, def: 2 },
    cultivateClick: 3,
    cultivatePassive: 4,
    mark: '荒',
    vaultable: true,
  },
  {
    id: 'mountain_river',
    name: '山河车残轮',
    description: '修炼槽。转一下，灵气就沉重地涌来。',
    lore: '仙逆',
    cost: 2e4,
    minRealm: 3,
    slot: 'cultivate',
    attrs: { spirit: 4 },
    cultivateClick: 2,
    cultivatePassive: 6,
    mark: '车',
    vaultable: true,
  },
  {
    id: 'dao_seed',
    name: '道种一枚',
    description: '修炼槽。大道将成时显化的种子。',
    lore: '大道',
    cost: 0,
    minRealm: 10,
    slot: 'cultivate',
    attrs: { spirit: 8, bone: 8, luck: 5 },
    cultivateClick: 20,
    cultivatePassive: 40,
    mark: '种',
    vaultable: true,
  },
  // —— 辅助 ——
  {
    id: 'storage_pouch',
    name: '下品储物袋',
    description: '辅助槽。能装灵草，也能装梦想。',
    lore: '诸天通用',
    cost: 400,
    minRealm: 0,
    slot: 'assist',
    attrs: { luck: 2 },
    mark: '袋',
    vaultable: false,
  },
  {
    id: 'spirit_boat',
    name: '破旧灵舟',
    description: '辅助槽。速度一般，逃命一流。',
    lore: '凡人修仙',
    cost: 8_000,
    minRealm: 2,
    slot: 'assist',
    attrs: { spd: 6, def: 1 },
    mark: '舟',
    vaultable: true,
  },
  {
    id: 'soul_lamp',
    name: '魂灯一盏',
    description: '辅助槽。照见心魔，也照见偷功法的。',
    lore: '仙逆',
    cost: 0,
    minRealm: 4,
    slot: 'assist',
    attrs: { spirit: 6, luck: 2 },
    combatMult: 1.03,
    mark: '灯',
    vaultable: true,
  },
  {
    id: 'plot_armor',
    name: '剧情护甲',
    description: '辅助槽。作者亲女儿限定。挨打也能站起来。',
    lore: '元梗',
    cost: 0,
    minRealm: 0,
    slot: 'assist',
    attrs: { def: 5, luck: 6 },
    combatMult: 1.06,
    mark: '甲',
    vaultable: true,
  },
  {
    id: 'cauldron_lid',
    name: '青铜鼎盖',
    description: '辅助槽。盖上能砸人，揭开能装逼。',
    lore: '遮天',
    cost: 4e4,
    minRealm: 4,
    slot: 'assist',
    attrs: { def: 6, spirit: 3, luck: 1 },
    mark: '鼎',
    vaultable: true,
  },
  {
    id: 'heaven_stele',
    name: '残破天碑',
    description: '辅助槽。碑上字看不清，但你感到「道」。',
    lore: '遮天/诸天',
    cost: 5e5,
    minRealm: 6,
    slot: 'assist',
    attrs: { spirit: 8, bone: 3, luck: 3 },
    combatMult: 1.05,
    mark: '碑',
    vaultable: true,
  },
];

/** 天才地宝：不占槽，直接加灵气 + 本世永久被动 */
export const NATURALS: NaturalDef[] = [
  {
    id: 'nat_spirit_grass',
    name: '百年灵草',
    description: '入口清凉，灵气立涨。',
    lore: '凡人',
    minRealm: 0,
    lingqiGain: 400,
    passiveBonus: 0.3,
    mark: '草',
    weight: 3,
  },
  {
    id: 'nat_beast_core',
    name: '一阶妖丹',
    description: '腥香扑鼻，炼化后底盘更厚。',
    lore: '凡人',
    minRealm: 1,
    lingqiGain: 1_200,
    passiveBonus: 0.8,
    mark: '丹',
    weight: 2,
  },
  {
    id: 'nat_fire_crystal',
    name: '地心火晶',
    description: '烫手，但吞下去修炼如坐火山口。',
    lore: '斗破',
    minRealm: 2,
    lingqiGain: 4_000,
    passiveBonus: 1.5,
    mark: '晶',
    weight: 2,
  },
  {
    id: 'nat_void_flower',
    name: '虚空莲瓣',
    description: '摘一片，寿元似有所感。',
    lore: '遮天',
    minRealm: 3,
    lingqiGain: 1.2e4,
    passiveBonus: 3,
    mark: '莲',
    weight: 1,
  },
  {
    id: 'nat_soul_dew',
    name: '神魂甘露',
    description: '一滴入识海，杂念退散。',
    lore: '仙逆',
    minRealm: 3,
    lingqiGain: 1e4,
    passiveBonus: 2.5,
    mark: '露',
    weight: 1,
  },
  {
    id: 'nat_dragon_blood',
    name: '龙血残渣',
    description: '腥烈，根骨隐隐发烫。',
    lore: '诸天',
    minRealm: 4,
    lingqiGain: 5e4,
    passiveBonus: 5,
    mark: '龙',
    weight: 1,
  },
  {
    id: 'nat_heaven_marrow',
    name: '天髓一缕',
    description: '罕见至极，灵力如潮。',
    lore: '遮天',
    minRealm: 6,
    lingqiGain: 5e5,
    passiveBonus: 12,
    mark: '髓',
    weight: 1,
  },
  {
    id: 'nat_dao_fruit',
    name: '半颗道果',
    description: '咬一口，像被天道瞪了一眼。',
    lore: '大道',
    minRealm: 8,
    lingqiGain: 8e6,
    passiveBonus: 30,
    mark: '果',
    weight: 1,
  },
];

/**
 * 主线剧情：由随机事件池触发，按 mainChapter 顺序推进。
 * 机缘为主，不全是战斗。
 */
export const MAIN_STORY: StoryEventDef[] = [
  {
    id: 'main_1_sect',
    title: '【主线】外门记名',
    body: '宗门外门招人。你可以用灵石买个记名，也可以去猎妖证明自己。凡人开局经典二选一。',
    minRealm: 0,
    lore: '凡人修仙·主线',
    mainChapter: 1,
    repeatable: false,
    options: [
      {
        id: 'm1_buy',
        label: '砸灵石记名',
        blurb: '花灵气入门，得储物袋与一点面子。',
        lingqiDelta: -150,
        grantTreasureId: 'storage_pouch',
        freePointsDelta: 1,
        flags: ['main_sect'],
      },
      {
        id: 'm1_hunt',
        label: '猎妖证明',
        blurb: '打一场；胜则入门，败不致死。',
        combatEnemyId: 'demon_wolf',
        deathOnLose: false,
        grantTreasureId: 'spirit_gather_jade',
        flags: ['main_sect'],
        freePointsDelta: 1,
      },
    ],
  },
  {
    id: 'main_2_market',
    title: '【主线】坊市风云',
    body: '坊市出现一份残卷拍卖。有人说是焚诀，有人说是骗局。你的气运在骰子上跳舞。',
    minRealm: 1,
    lore: '斗破/凡人·主线',
    mainChapter: 2,
    options: [
      {
        id: 'm2_bid',
        label: '咬牙竞拍',
        blurb: '可能拍到焚诀残页，也可能被割韭菜。',
        lingqiDelta: -3_000,
        grantTreasureId: 'flame_tome',
        flags: ['main_market'],
        attrsDelta: { luck: -1, atk: 1 },
      },
      {
        id: 'm2_steal_look',
        label: '神识偷瞄',
        blurb: '记下三行口诀，染上「小偷」闲话。',
        flags: ['main_market', 'thief_name'],
        attrsDelta: { spirit: 2, luck: -1 },
        lingqiDelta: 200,
      },
      {
        id: 'm2_leave',
        label: '冷静离场',
        blurb: '不赌。得百年灵草机缘。',
        flags: ['main_market'],
        freePointsDelta: 1,
        lingqiDelta: 800,
        grantNaturalId: 'nat_spirit_grass',
      },
    ],
  },
  {
    id: 'main_3_secret',
    title: '【主线】秘境开启',
    body: '界域秘境裂缝张开。里面有天才地宝的气味，也有老怪的呼吸。',
    minRealm: 2,
    lore: '诸天·主线',
    mainChapter: 3,
    options: [
      {
        id: 'm3_deep',
        label: '直闯深处',
        blurb: '高风险：遇老怪；高收益：虚空莲瓣。',
        combatEnemyId: 'soul_old',
        deathOnLose: false,
        flags: ['main_secret'],
        attrsDelta: { atk: 2 },
        grantNaturalId: 'nat_void_flower',
      },
      {
        id: 'm3_edge',
        label: '外围捡漏',
        blurb: '稳妥得妖丹与灵气。',
        flags: ['main_secret'],
        lingqiDelta: 5_000,
        freePointsDelta: 1,
        grantNaturalId: 'nat_beast_core',
      },
      {
        id: 'm3_map',
        label: '卖地图赚钱',
        blurb: '凡人式选择：不装英雄，先搞钱。',
        flags: ['main_secret', 'sold_map'],
        lingqiDelta: 1.5e4,
        attrsDelta: { luck: 1 },
      },
    ],
  },
  {
    id: 'main_4_tribulation_rumor',
    title: '【主线】天劫预言',
    body: '有人立牌：「三年后此间有劫。」你想起斗破的三年之期，笑了笑，又笑不出来。',
    minRealm: 4,
    lore: '斗破梗·主线',
    mainChapter: 4,
    options: [
      {
        id: 'm4_prepare',
        label: '闭关备劫',
        blurb: '属性稳增，得剧情护甲（心理安慰）。',
        flags: ['main_trib_ready'],
        grantTreasureId: 'plot_armor',
        attrsDelta: { def: 3, bone: 2 },
        freePointsDelta: 2,
      },
      {
        id: 'm4_ignore',
        label: '预言不可信',
        blurb: '继续浪。气机+2，但无准备。',
        flags: ['main_trib_ignore'],
        attrsDelta: { luck: 2 },
        lingqiDelta: 2e4,
      },
    ],
  },
  {
    id: 'main_5_dao_ask',
    title: '【主线】问道残碑',
    body: '天碑半截立于云上。碑文模糊，却像在问：你为何修仙？',
    minRealm: 6,
    lore: '遮天/大道·主线',
    mainChapter: 5,
    options: [
      {
        id: 'm5_power',
        label: '为了变强',
        blurb: '攻伐道心。得残破天碑。',
        flags: ['main_dao_power'],
        grantTreasureId: 'heaven_stele',
        attrsDelta: { atk: 4, spirit: 2 },
      },
      {
        id: 'm5_live',
        label: '为了活着',
        blurb: '凡人真心。护体与气机上升。',
        flags: ['main_dao_live'],
        attrsDelta: { def: 4, luck: 3 },
        freePointsDelta: 2,
      },
      {
        id: 'm5_void',
        label: '为了看见更高处',
        blurb: '问虚之念。神识大涨。',
        flags: ['main_dao_void'],
        attrsDelta: { spirit: 5, spd: 2 },
        lingqiDelta: 1e5,
      },
    ],
  },
];

export function getNatural(id: string): NaturalDef | undefined {
  return NATURALS.find((n) => n.id === id);
}
